### ISSUE TITLE
New design for website coming soon

### ISSUE THREAD

**Issue by soundbit** [ethereumclassic/ethereumclassic.github.io#10]
by http://etherdesign.io

**Comment by ProphetDaniel** [comment]
That is great, soundbit!

**Comment by Panguexe** [comment]
Thanks, that is really great !

**Comment by soundbit** [comment]
Кто здесь говорит на русском языке?

**Comment by arvicco** [comment]
@soundbit English is a universal language of Github that is preferable to keep dev community together and on the same page. You can open a separate topic for Russian-language site discussion if this is convenient for you.

**Comment by NDNewell** [comment]
@soundbit Hi **bit_novosti** informed me that you've been tasked with creating the website and would like to help in any way possible.

**Comment by matthewjamesr** [comment]
Do we have a more defined date than coming soon? If it is something that will take more than two weeks I would like to commit a stop-gap just to tidy things up till then.

**Comment by soundbit** [comment]
We are working on it, you can make suggestions for corrections 

https://drive.google.com/file/d/0B4Zk1YVspqesVkpvVmNRRjdkZUk/view 

http://issuu.com/1081/docs/etc_design?workerAddress=ec2-54-197-35-162.compute-1.amazonaws.com

**Comment by Machete3000** [comment]
New design is looking good!

**Comment by Machete3000** [comment]
The new design text/copy needs review and some editing. Please create a repo for the new site. I extracted all the text from the PSD file and would like to upload it so that we can collaborate on it.

**Comment by Machete3000** [comment]
http://pastebin.com/Jk81EjGX

**Comment by soundbit** [comment]
@Panguexe @ProphetDaniel you can do a structured wiki page?

**Comment by realcodywburns** [comment]
Looks good.I agree w/ machete on changing wording on a few parts. That being said, the faster the site is up the better. Ethereum<sup>classic</sup> is in the news and public space daily. Not just altcoin news, US finincial news. We need to drive early adapters to a safe, good looking site.

**Comment by ProphetDaniel** [comment]
I started making the wiki. Contributions are welcome. [Ethereum<sup>classic</sup>'s wiki](https://github.com/ethereumclassic/ethereumclassic.github.io/wiki)

**Comment by NDNewell** [comment]
@soundbit we need an update. When will design be finished? When will coding be finished? Please inform.
