### ISSUE TITLE
Headlines are showing really small on the Desktop version of the website

### ISSUE THREAD

**Issue by ghost** [ethereumclassic/ethereumclassic.github.io#1014]
For the FAQ I suggest a popup or a removable banner, shrink the first image and headlines larger with maybe a preview.
That's something I would like to contribute to but I'm not familiar with the Gatsby framework, so If I can prepare something for this, just let me know.

**Comment by TheCrowbill** [comment]
This issue has been open for several months and has become stale. Has the issue been resolved?

I am unable to reproduce small headlines on the live website. If the problem still persists, please post a link to the specific page of the website that needs attention.

If resolved, please close this issue. If there is no update forthcoming, I will close this issue in a few days. Thanks!

**Comment by TheCrowbill** [comment]
Closing this stale issue.

If more information about the problem becomes available or someone recreates it, the issue can be reopened.
