### ISSUE TITLE
Adding NOW Wallet to the list of ETC wallets 

### ISSUE THREAD

**Issue by WalletNOW** [ethereumclassic/ethereumclassic.github.io#1117]
Hello, Team!

NOW Wallet (walletnow.app) is a non-custodial wallet developed by the team of ChangeNOW Exchange Service that supports supports over 40 blockchains, including BTC, ETH, ETC, DOGE, and XMR, as well as over 500 cryptocurrencies.

With its built-in ChangeNOW exchanger, NOW Wallet enables instant crypto-to-crypto and fiat-to-crypto exchanges, as well as a variety of other advanced features. While a relatively new product – a bit over a year old – NOW Wallet has already proven to be a top-performing wallet, surpassing many established ones.

NOW Wallet Supports Ethereum Classic. I've been wondering whether it's possible to include NOW Wallet in the list of supported Software Wallets on your website.

**Comment by TheCrowbill** [comment]
@WalletNOW the NOW Wallet has been listed on the ETC website since PR #937.

If there is an error in the listing please reopen this issue.
