### ISSUE TITLE
npm ERR! code EINVALIDTAGNAME

### ISSUE THREAD

**Issue by jileilei** [ethereumclassic/ethereumclassic.github.io#145]
my  npm version is 5.3.0, node version is  v6.11.1

follow is shows by # npm install  
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated ignore@3.1.5: several bugs fixed in v3.2.1
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
**npm ERR! code EINVALIDTAGNAME**
**npm ERR! Invalid tag name "1.3,0": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-19T16_06_04_127Z-debug.log**

**Comment by realcodywburns** [comment]
is this still an issue, cannot duplicate

**Comment by realcodywburns** [comment]
added to trello for tracking: https://trello.com/c/Jtm6Hfrf

**Comment by realcodywburns** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [npm ERR! code EINVALIDTAGNAME #145](https://trello.com/c/Jtm6Hfrf/3-npm-err-code-einvalidtagname-145)

**Comment by bobsummerwill** [comment]
I fixed this.
