### ISSUE TITLE
Update Bootstrap Chaindata torrent link

### ISSUE THREAD

**Issue by ghost** [ethereumclassic/ethereumclassic.github.io#149]
For downloading chaindata torrent which the link is located in ETC Nodes button, , the original torrent link https://mega.nz/#!UVM2FDAR!c0cF6qKy4IAsu7VRXiAAgHGzSMOSVufB7WHNojsM7yw doesn't work since there are no seeders. Therefore, I'd like to change the mega.nz link to http://www.blockchaindownload.kr/ethereum-etc site, serves bitcoin, ethereum, ethereum-classic blockchain data backups.

**Comment by realcodywburns** [comment]
I have requested evaluation of the file to verify its authenticity

**Comment by splix** [comment]
I don't think it's a good idea, w/o automatic state verification is a dangerous way of distributing blockchain history

**Comment by realcodywburns** [comment]
added to trello for tracking and eval: https://trello.com/c/9XujcBL8

**Comment by realcodywburns** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Bootstrap Chaindata torrent link #149](https://trello.com/c/9XujcBL8/2-update-bootstrap-chaindata-torrent-link-149)

**Comment by pyskell** [comment]
Is this necessary now with the speed of warp/fast sync in geth/parity?

You can get the entire blockchain synced in 20 minutes.

Also agree with @splix this approach is dangerous and was more of a stop-gap in the early days.

**Comment by bobsummerwill** [comment]
No.
