### ISSUE TITLE
Please keep ethereumclassic/README in sync with ethereumclassic.github.io

### ISSUE THREAD

**Issue by arvicco** [ethereumclassic/ethereumclassic.github.io#17]
I appreciate efforts our org members and volunteers put into updating ethereumclassic.github.io with the latest news and developments. Please keep in mind though that the content of https://github.com/ethereumclassic/README should be kept in sync with changes on the website (at least until such time as a new website design is ready).

**Comment by Panguexe** [comment]
Done @arvicco , please check it again.

**Comment by ProphetDaniel** [comment]
This task is also going to be needed even after the new website is live. So maybe we should find out an automated way of performing this task.

**Comment by arvicco** [comment]
I agree, some kind of automation is advisable but it takes time.

**Comment by NDNewell** [comment]
How can we go about automating it?
