### ISSUE TITLE
Hackers should be welcome!

### ISSUE THREAD

**Issue by ProphetDaniel** [ethereumclassic/ethereumclassic.github.io#18]
Hackers have a great set of skills and are objective in pinpointing system vulnerabilities. So In my understanding hackers should be attracted to the organization even if for that to be effective we need to take actions consonant with the psychological understanding of a [hacker`s mind](http://eandt.theiet.org/magazine/2014/01/get-your-head-around-hacker-psychology.cfm). Community must feel embraced to help on that.

Should we offer bounties? Should we help making hackers famous? How do we evangelize them with our moral principles and our democratic sense of organization?

**Comment by etherx-dev** [comment]
Bounties for what exactly? Also this is an issue section for ethereumclassic.coms Github.

Please use https://ethereumclassic.slack.com for general discussion.
