### ISSUE TITLE
Guides

### ISSUE THREAD

**Issue by whatisgravity** [ethereumclassic/ethereumclassic.github.io#19]
Currently mists links to:

https://www.ethereum.org/crowdsale
https://www.ethereum.org/cli#geth
https://www.ethereum.org/token

It would be nice if these can be included in our community site, so our version of Mist links to our site.

**Comment by ProphetDaniel** [comment]
The links were added to the footer area of the main page. Missing to update the pictures to better represent each page.

**Comment by realcodywburns** [comment]
Is it possible to modify one of them to point to a 'send with replay protection' how to instead of one of the other default how-to's?  We will have to build the pages out either way. This would make mist less of a clone.

**Comment by NDNewell** [comment]
@ProphetDaniel @whatisgravity - Is it necessary to have this live already? IMHO it's not helping our marketing efforts to display a skeleton/incomplete section as our live site as it's not really aesthetically pleasing. Also, it doesn't seem related to the content we currently have up. As I see it, for now the placeholder site is a guide on what is being done to build up ETC and resources for doing so. 'Features' of ETC, such as the links provided, can eventually be added to the new site... what do you think?

**Comment by whatisgravity** [comment]
In my opinion the best solution is to complete them but if we are unable to do that, before I release Mist I will change the links so they do not link to incomplete pages.
