### ISSUE TITLE
https://ethereumproject.github.io/etherwallet/ problem

### ISSUE THREAD

**Issue by onur1980** [ethereumclassic/ethereumclassic.github.io#197]
hi,

does anyone know what happened to https://ethereumproject.github.io/etherwallet/ ?? my exp is there and i can't open the page. it gave the error below.

thanks.

There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

**Comment by bobsummerwill** [comment]
Old issue.  Site changed a bunch.  Please log new issue if it is still a problem.  Thanks.
