### ISSUE TITLE
Determine content & structure

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#207]
The new version of the website should include content migrated from https://wordpress.ethereumclassic.org/, including:

- Landing Page
- Education
- Teams
- Roadmap
- Resources
- Community
- Powered by ETC
- Blog

I think this wordpress site structure is good.

That being said, we'll have the opportunity to easily modify the structure or add additional information to the site during the migration. Are there any suggestions for modifying this or should we copy it exactly?

**Comment by bobsummerwill** [comment]
Let's just go one-to-one.
We can iterate from there.
Thanks

**Comment by bobsummerwill** [comment]
This can be closed now, right?
Are you ready to submit changes for the restructuring yet?

**Comment by hitchcott** [comment]
There's been some debate in doscord as to how far we should go with including various projects in the ETC ecosystem. Specifically regarding:

- Dapps
- Mining Pools
- Wallets
- Exchanges
- Teams / Individuals

The one extreme is to allow everything. The other is to allow nothing.

Personally I think we should list everything (apart from confirmed scams).

Discuss.

**Comment by TheEnthusiasticAs** [comment]
Agree partially: I would only list essential stuffs: Wallet(s), block explorer(s), nodes, dapps - primary built on/for ETC eco, teams/individuals.
Things without which the eco can not exist on the first line

**Comment by bobsummerwill** [comment]
This is good enough, eh?
We are live and will iterate from there.
