### ISSUE TITLE
Website banner notification for fork dates

### ISSUE THREAD

**Issue by realcodywburns** [ethereumclassic/ethereumclassic.github.io#224]
As a website visitor, I would like to be notified of the date of the next hardfork. 

The baner should direct a user where to find more information  on the fork and estimate the date and time of the fork.

**Comment by TheEnthusiasticAs** [comment]
The red dummy pop-upper already was intergrated in to the new upcoming website. It needs to be filled with infos after the agharta call

**Comment by bobsummerwill** [comment]
So this exists now.
But needs updating for Agharta with actual block numbers (only available for Mordor and Kotti at the moment), but let's make this real right now.

**Comment by hitchcott** [comment]
Can do - what content should it contain?

**Comment by bobsummerwill** [comment]
Ethereum Classic is undergoing a planned upgrade "Agharta" around 15 Jan 2020.
If you run an ETC node please [upgrade](https://ecips.ethereumclassic.org/ECIPs/ecip-1056) as soon as possible.

We can tweak the language as we go, probably wanting a landing URL on this webpage which we link to.

Thanks!
