### ISSUE TITLE
Add netlify Integration

### ISSUE THREAD

**Issue by realcodywburns** [ethereumclassic/ethereumclassic.github.io#227]
add integration for netfly:

#### add app to org
- [x] allow application
#### configuration
- [x] add repo to netfly
- [x] create build pipeline
- [ ] configure dns to point to inspiring-cori-dcb0d2.netlify.com 
- [ ] add tls cert

**Comment by hitchcott** [comment]
Merge previews are now working.

See https://github.com/ethereumclassic/ethereumclassic.github.io/pull/229

For now I guess we can close this issue unless we want to use Netlify for the main deploy (but for now github works fine).

**Comment by realcodywburns** [comment]
closing per above
