### ISSUE TITLE
Image preview does not work nicely.  Can we fix it?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereumclassic/ethereumclassic.github.io#232]
See https://photos.app.goo.gl/sJSQdGw2GD6JVXBx5.

Where the preview from https://medium.com/ethereum-classic/etc-cooperative-applying-to-join-eea-3f89bb3c71d4 works marvellous when cut-and-pasting a link into a Twitter DM.

But https://ethereumclassic.org/blog/2019-10-18-etc-coop-joins-eea/ does nothing.

We must be missing some HTML magic.  Any idea, @hitchcott or others?

**Comment by hitchcott** [comment]
Fixed in v2 branch
