### ISSUE TITLE
Revamp the Roadmap page, following ETH's example

### ISSUE THREAD

**Issue by bobsummerwill** [ethereumclassic/ethereumclassic.github.io#235]
https://eth.wiki/en/roadmap
https://eth.wiki/en/roadmap/istanbul

And see also the Constantinople section on the main page, with links to press articles.
We could do that for Atlantis very easily.

I think this textural format is very good for software developers, where the visual timeline is really just for the peanut gallery.

Also, the Development Plans for 2019-2020 is garbage, with a whole load of ETCDEV aims in there which are not reflective of the current reality.   Let me give myself a TODO to create a PR with edits to that.

**Comment by TheEnthusiasticAs** [comment]
The first part is ok for me. 

The second: The Development Plans for 2019-2020 was introduced by ETC Core: https://medium.com/etclabscore/introducing-etc-labs-core-an-etc-core-development-team-c46413c1ab50. The roadmap can be rephrased / extended, but I would not take them off.

**Comment by bobsummerwill** [comment]
OK - great.

If it is from ETC Core, that is fine.

I was thinking it was still cut-and-paste from ETCDEV plans - from here:

    https://wordpress.ethereumclassic.org/roadmap/

Including Mantis plans (which are dead) or Orbita plans (which are dead).

As things continue to take shape around Atzlan and onwards, we can refine this roadmap as we go.

We also have https://github.com/orgs/ethereumclassic/projects/1, thanks to @realcodywburns

**Comment by TheEnthusiasticAs** [comment]
Yes, the roadmap should be updated with new infos as soon as they are available. The AZTLÁN is already as place keeper there. 

Yeah, like that work progress plan too (btw. the picture is by me :-) ).

**Comment by gitr0n1n** [comment]
Similar card, but content: https://github.com/ethereumclassic/ethereumclassic.github.io/issues/332

**Comment by hitchcott** [comment]
To add:
https://medium.com/etc-core/etc-core-2020-roadmap-announcement-c2166cdbc53d
