### ISSUE TITLE
Add the birth of the ETC Coop to the timeline on the webiste

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#239]
@TheEnthusiasticAs ETC Cooperative legal entity was created Sep 2017 as LLC.
Application for non-profit status was made May 2018 and approved Nov 2018, retroactive to the date of application.

If you add the entry in, and tag me for review, I can help with the language.

_Originally posted by @bobsummerwill in https://github.com/ethereumclassic/ethereumclassic.github.io/issues/186#issuecomment-557909498_

**Comment by hitchcott** [comment]
Ref #186
