### ISSUE TITLE
Remove not trusted mining pools (if any)

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#240]
I only removed the mining pools who's websites are dead.

Would be ideal to have some mining person in the know advise which ones should stay.

**Comment by gitr0n1n** [comment]
I think its okay to limit the miners to the top 5 hash power with a link to a bigger view.

https://github.com/ethereumclassic/ethereumclassic.github.io/wiki/Content:-Mining-Pools

**Comment by TheEnthusiasticAs** [comment]
Either as much as possible minings pools (other operators the same) will be added or no one. ETC is permissionless, which should be mirrored in all possible ways. Also, it will unfair to other.

**Comment by gitr0n1n** [comment]
Okay, I have a more complete list here for the restructure.

https://github.com/ethereumclassic/ethereumclassic.github.io/issues/321

https://github.com/ethereumclassic/ethereumclassic.github.io/wiki/3.3.---Mining-Resources
