### ISSUE TITLE
Add day 2 videos from ETC summit

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#241]
@bobsummerwill if you can let me know when these are ready, I'll spruce up the summit page a little bit with these additional videos (and add a menu listing the topics).

**Comment by bobsummerwill** [comment]
Let's delay, please!

**Comment by gitr0n1n** [comment]
I think this would be nice in a "Media/Blog/Press" section for RSS feed and documented coverage.

ETC Summit Archives, Public appearances by notable ETC teams. Like Terry's $1M charity donation interview. Bob and Kevin's Messari AMA.

Regarding these video's. I've timestamped them all on my twitter feed when I watched them. At a minimum we can link that way and get this content online. It's going stale sitting in the shadows.

ETC Summit 2019 Timestamp and descriptions.
https://twitter.com/LongSats/status/1201462189241978883?s=20

If we are trying to get spliced vids. I could look into something to cut them up and knock it out over a night or two.

I'd prefer linking via youtube timestamp to keep the views aggregated on the whole conference talk.

**Comment by TheEnthusiasticAs** [comment]
With "Media/Blog/Press" section I am with it.
Announcements like $1M charity donation, should stay on contributors's website. Bob is also going to remove ETCCoop blogs. More details Bob posted on Discord, which I also joining:
![image](https://user-images.githubusercontent.com/48069525/73292320-2537c080-4202-11ea-8809-2f46cfd41f53.png)

**Comment by hitchcott** [comment]
Yeah, on the (very) old site there was a 'media' list of links to external sites. 

I'm okay with including external links like this to show activity and help promote the ecosystem.

**Comment by TheEnthusiasticAs** [comment]
There are already website links of the ETC participants, like etclabs, etccoop, ... . I would not include the links of their blogs, otherwise the maintainers of the etc website have an additional task to check, whether those are outdated. The site should only be for onboarding. Nothing more

**Comment by gitr0n1n** [comment]
@hitchcott 

We have the Main youtube video for the Summit. I think we should just link to that video with proper timestamps.

Here is a Twitter twitter thread with proper timestamps and attribution for each talk to use that as a reference. An added benefit to this is that our "views" will be aggregated to one video and perhaps people will keep watching the WHOLE conference and no isolated talks.

https://twitter.com/LongSats/status/1201462189241978883?s=20

**Comment by bobsummerwill** [comment]
Yes, you could just use those for now, and then we can swap in for the individual videos as they become available.

I have posted all the individual talks for Day 1 now, and those at least could be added.

As well as creating Day 2 individual videos, I still need to gather all the slides too.   I had hosted those on the etccooperative wordpress site for the ones already linked for Day 1, but those should all really just get inlined into the website.

**Comment by bobsummerwill** [comment]
We cannot really inline the videos themselves, though.   They are way too big.

**Comment by gitr0n1n** [comment]
## Conferences
- [ETC Summit 2017](https://etcsummit.com/2017-summit/)
- [ETC Summit 2018](https://etcsummit.com/2018-etc-summit/)
- [ETC Summit 2019](https://etcsummit.com/)
  + [Full Day 1 - October 3rd, 2019](https://www.youtube.com/watch?v=Msi6EItbslk&list=PL20HSZ6AK2yOSOhBGFtLj6zPLkJEm_3FF&index=6) - ETC Summit 2019
    + [Opening Address](https://youtu.be/Msi6EItbslk?t=1655) by Bob Summerwill [@BobSummerwill](https://twitter.com/BobSummerwill), Executive Director of [ETC Cooperative](https://etccooperative.org/).
    + [The State of Ethereum Classic](https://youtu.be/Msi6EItbslk?t=3205) by Anthony Lusardi [@pyskell](https://twitter.com/pyskell), Former Executive Director of [ETC Cooperative](https://etccooperative.org/).
    + [Ethereum Classic Principles, Vision & Opportunity](https://youtu.be/Msi6EItbslk?t=3790) by Donald McIntyre [@MyEtherPlan](https://twitter.com/MyEtherplan), Researcher, Writer, & Podcaster [Etherplan](https://etherplan.com/).
    + [Atlantis Protocol Upgrade & The ETC Roadmap](https://youtu.be/Msi6EItbslk?t=5375) by Afri Schoeden [@a4fri](https://twitter.com/a4fri), [Ethereum Classic](https://ethereumclassic.org/) Core Developer.
    + [The Future of JSON-RPC Tooling](https://youtu.be/Msi6EItbslk?t=8290) by Shane Jonas [@shanejonas](https://twitter.com/shanejonas), Co-Lead Tooling Developer at [ETC Core](https://etccore.io/).
    + [Bridging the Decentralized Services Gap](https://youtu.be/Msi6EItbslk?t=8795) by Zane Starr [@zanecstarr](https://twitter.com/zanecstarr), Tooling Developer at [ETC Core](https://etccore.io/).
    + [Adding Merkle-Mountain-Ranges and Fly-Proofs to ETC](Link) by Zac Mitton [@VoltzRoad](https://twitter.com/VoltzRoad), Open Source Software Engineer at [Voltz Road](https://voltzroad.com/).
    + [Ethereum Classic's ECIP-1050: One Byte of Context](https://youtu.be/Msi6EItbslk?t=11350) by Brooklyn Zelenka [@expede](https://twitter.com/expede), Co-Founder/CTO of [FISSION](https://fission.codes/).
    + [The Year Ahead for Ethereum Classic Labs](https://youtu.be/Msi6EItbslk?t=15290) by Terry Culver [@realetclassic](https://twitter.com/realetclassic), CEO of [Ethereum Classic Labs](https://etclabs.org/) & [ETC Core](https://etccore.io/).
    + [Infrastructure for Decentralizing Distributed Networks](https://youtu.be/Msi6EItbslk?t=16455) by Aaron Lowry [@Aaron_Lowry](https://twitter.com/Aaron_Lowry), Co-Founder/CEO of [Ethernode](https://ethernode.io/).
    + [Radical Ideals: Experiments in Sustaining Open Source Software](https://youtu.be/Msi6EItbslk?t=18250) by Scott Moore [@notscottmoore](https://twitter.com/notscottmoore), Developer Relations Lead at [GitCoin](https://gitcoin.co/).
    + [POA Network: Development Tools in the ETC Ecosystem](https://youtu.be/Msi6EItbslk?t=21060) by Andrew Gross [@poanetwork](https://twitter.com/poanetwork), Technical Writer for [POA Network](https://www.poa.network/).
    + [State of the Ethereum Classic Testnets](https://youtu.be/Msi6EItbslk?t=23515) by Afri Schoeden [@a4fri](https://twitter.com/a4fri), [Ethereum Classic](https://ethereumclassic.org/) Core Developer.
    + [Metronome - First Cross-Chain #Cryptocurrency: Chain Hop From ETH to ETC](https://youtu.be/Msi6EItbslk?t=25170) by Manoj Patidar [@manojpatidarr](https://twitter.com/manojpatidarr), Principal Engineer at [Bloq](https://www.bloq.com/).
    + [Fireside Chat: Improving Investor Access to Ethereum Classic](https://youtu.be/Msi6EItbslk?t=26080) by Michael Sonnenshein [@Sonnenshein](https://twitter.com/Sonnenshein), Managing Director of [Grayscale](https://grayscale.co/).
    + [The Need for Cross Chain Collaboration](https://youtu.be/Msi6EItbslk?t=27755) by Aidan Hyman [@Aidan_IH](https://twitter.com/Aidan_IH), Co-Founder/CEO of [ChainSafe](https://chainsafe.io/).
    + [Developer Relations in Ethereum Classic](https://youtu.be/Msi6EItbslk?t=29190) by Yaz Khoury [@Yazanator](https://twitter.com/Yazanator), Director of Developer Relations at [ETC Cooperative](https://etccooperative.org/).
  + [Full Day 2 - Octover 4th, 2019](https://www.youtube.com/watch?v=TNsWR7jXllQ&list=PL20HSZ6AK2yOSOhBGFtLj6zPLkJEm_3FF&index=7) - ETC Summit 2019
    + [A New Open Source Deal for Web3](https://youtu.be/TNsWR7jXllQ?t=3240) by Boris Mann [@bmann](https://twitter.com/bmann), Co-Founder of [FISSION](https://fission.codes/).
    + [Positive Sum Games Between Ethereum & Ethereum Classic](https://youtu.be/TNsWR7jXllQ?t=5945) by Virgil Griffith [@virgilgr](https://twitter.com/virgilgr), Special Projects at the [Ethereum Foundation](https://ethereum.org/).
    + [A Peripheral Observer and Fan's View of Ethereum Classic]() by Sunny Aggarwal [@sunnya97](https://twitter.com/sunnya97), Researcher & Core Dev at [Tendermint](https://tendermint.com/) & [Cosmos](https://cosmos.network/).
    + [Is Open Source Software Immortal?](https://youtu.be/TNsWR7jXllQ?t=9560) by Zachary Belford [@belfordz](https://twitter.com/belfordz), Co-Lead Tooling Developer at [ETC Core](https://etccore.io/).
    + [Merging Blockchains: A Technical Perspective](https://youtu.be/TNsWR7jXllQ?t=11350) by Wei Tang [@sorpaas](https://twitter.com/sorpaas), Core Developer at [Parity](https://www.parity.io/).
    + [Ethereum Classic's EVM LLVM Project](https://youtu.be/TNsWR7jXllQ?t=12685) by Alan Li [@etc_core](https://twitter.com/etc_core), Lead Compiler Engineer at [ETC Core](https://etccore.io/).
    + [ECIP-1049: Why Ethereum Classic Should Adopt SHA3 Proof of Work](https://youtu.be/TNsWR7jXllQ?t=15310) by Alex Tsankov [@antsankov](https://twitter.com/antsankov), Open Source Developer at [Block Reaction](https://blockreaction.nyc/).
    + [Building Trust as a Miner or Miner-Maker](https://youtu.be/TNsWR7jXllQ?t=17315) by Nishant Sharma [@nishantsharma87](https://twitter.com/nishantsharma87), PR & Community Relations at [Bitmain](https://www.bitmain.com/).
    + [Ethereum Classic Ethash ASICs](https://youtu.be/TNsWR7jXllQ?t=18440) by Werner Almesberger [@LinzhiCorp](https://twitter.com/LinzhiCorp), System Architect at [Linzhi](https://linzhi.io/).
    + [ETC Summit Platform Panel: Afri Schoedon, Shane Jonas, Wei Tang, Zachary Belford, Zachary Mitton](https://youtu.be/TNsWR7jXllQ?t=23810) Moderated by Yaz Khoury [@Yazanator](https://twitter.com/Yazanator), Director of Developer Relations at [ETC Cooperative](https://etccooperative.org/).
    + [ETC Summit Community Panel: Chelsea Palmer, Donald McIntyre, Kevin Lord, Terry Culver, Yaz Khoury](https://youtu.be/TNsWR7jXllQ?t=25530) Moderated by Bob Summerwill [@BobSummerwill](https://twitter.com/BobSummerwill), Executive Director of [ETC Cooperative](https://etccooperative.org/).
    + ["Capture" Was Already Always Happening: The Complexity of Power in Blockchain Ecosystems](https://youtu.be/TNsWR7jXllQ?t=27480) by Chelsea Palmer [@chiselinc](https://twitter.com/chiselinc), Organizer of [DogeCon](http://www.dogecon.lol/).
    + [ETC Summit 2019: Closing Keynote](https://youtu.be/TNsWR7jXllQ?t=29745) by Charles Hoskinson [@IOHK_Charles](https://twitter.com/IOHK_Charles), Co-Founder/CEO of [IOHK](https://iohk.io/) & Co-Founder of the Ethereum Project.

**Comment by gitr0n1n** [comment]
That should be a good foundation of content to build the foundation of the page @hitchcott . You can find the raw markdown in my MasterList.

https://github.com/gitr0n1n/MasterList-EthereumClassic

**Comment by TheEnthusiasticAs** [comment]
FYI: There are no videos for 2017 and 2018 summits. I would note it brackets next to the years: 
- ETC Summit 2017 (no video contents available atm)
- ETC Summit 2018 (no video contents available atm)

**Comment by gitr0n1n** [comment]
Found the videos and posted on:
https://github.com/ethereumclassic/ethereumclassic.github.io/issues/339

We can probably close this card for now.

**Comment by bobsummerwill** [comment]
Thanks.  There are a couple of 2017 videos (see YouTube playlist).   2018 videos were posted on Anthony’s personal channel but then he deleted them.  I have the originals in Dropbox and have to go through the tedious process of uploading them all to YouTube.    If either you guys would like to do this tedious work yourselves I would have happy to give you ETC Coop YouTube and Dropbox logins

**Comment by gitr0n1n** [comment]
Closing this for husekeeping since we have an updated card with links at:
https://github.com/ethereumclassic/ethereumclassic.github.io/issues/339
