### ISSUE TITLE
Add ETC WeChat group

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#242]

**Comment by bobsummerwill** [comment]
Annoyingly, it looks like the WeChat QR code "runs out" within a month or so tops.

But yes, we should have links and QR code.

**Comment by TheEnthusiasticAs** [comment]
cant you renew it?

**Comment by bobsummerwill** [comment]
Here is a newer one, but we will have to keep refreshing this every month or so (which is fine):

https://photos.app.goo.gl/wDvnLVL1dhAdyBvh6

**Comment by bobsummerwill** [comment]
Or every week, even?   Not sure.  We will find out as we go.

**Comment by TheEnthusiasticAs** [comment]
can be there written a script for an auto-renewing?

**Comment by husainfazel** [comment]
To save on admin, how about we use generate own QR code which links to a URL that we can dynamically point towards the new QR code. Then it can be a case of committing a new URL instead of uploading new image etc.

**Comment by bobsummerwill** [comment]
"that we can dynamically point towards the new QR code"

That saves us nothing over refreshing this image periodically.   So let's just do that.   I will need to give myself a recurring task to update this image.

**Comment by husainfazel** [comment]
I meant dynamically point towards the new address... so the QR code remains static, you just need to login to the service in which you generated it and update the URL.

vs
1. Refreshing the QR code on WeChat
2. Downloading the new image
3. Uploading it to a public location
4. Committing the new location (might be skipped if you are overwriting the old one)

But if it's relatively simple to keep refreshing it, that's fine. 

These guys have a tutorial (but no link and I don't understand Chinese) for an app that allows multiple wechat QR codes to be stacked behind one QR code: http://www.programmersought.com/article/42055922/

**Comment by hitchcott** [comment]
I'm guessing it'll be easier and more elegant for me to create a component that dynamically generates the QR code from a string. Then someone will just need to update the string rather than upload a new image. That string can be found by scanning your phone screen on something like https://webqr.com/

**Comment by gitr0n1n** [comment]
I'm working on the cummonity page and pulled this QR code. I hope its relevant.
https://bobsummerwill.files.wordpress.com/2019/10/screen-shot-2020-01-31-at-11.40.10-pm.png?w=230&h=300

**Comment by bobsummerwill** [comment]
@gitr0n1n Annoyingly this QR code is always time-limited.
I have been having to regenerate every two weeks or so and refreshing the article.
We will need to do the same on the website.
(ie. I give myself a scheduled task every two weeks to refresh this.

**Comment by gitr0n1n** [comment]
that's pretty lame. are you sure there isn't a way for companies to create static qr codes?

**Comment by TheEnthusiasticAs** [comment]
Can't there be built a script, which auto-refreshes the QR? The steps could be:
- log on after a period of a XX time on XY wechat account
- create a QR
- push this as PR on git
- auto-approve on git
- push it to the website

**Comment by bobsummerwill** [comment]
Possibly, @TheEnthusiasticAs, but everything is a bit ugly with WeChat.   The web view is very much a second class citizen.   The mobile app is the first class entity.   I do not think that is any public API and automation is not supported or encourages.  Is probably a breach of the TOS and could be the user account doing it banned.    They do not make it easy.   Just a manual task every two weeks, while ugly, is likely the pragmatic solution.  Anybody could do that grunt work.

**Comment by TheEnthusiasticAs** [comment]
It is an argument with banning. Then let's do it as you proposed
