### ISSUE TITLE
Switch to Mailchimp (or similar) for newsletter sign up

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#243]
This will enable us to remove the old wordpress website, which is currently being used for mailing list.

**Comment by bobsummerwill** [comment]
Does the current form WORK?
Mucky, I know, but functional?

**Comment by hitchcott** [comment]
Yes, it works now.

**Comment by bobsummerwill** [comment]
We will actually just strip this out entirely.
It is an ETC Cooperative newsletter, not an ETC newsletter, so this is not the right site for the sign-up form.

**Comment by hitchcott** [comment]
Fixed via #296
