### ISSUE TITLE
More content / links for Knowledge Base

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#244]
The knowledge base is open to various authors / new topics, and can link to good ETC concepts around the web.

**Comment by bobsummerwill** [comment]
Best of all is pulling actual content in here.

Particularly for the etherplan.com pasts, it would be best to inline the content (with appropriate credit and consent).

**Comment by TheEnthusiasticAs** [comment]
joining Bob. I checked etherplan few days ago. The works are going till 2015 - ETC related.

**Comment by gitr0n1n** [comment]
I'd like to see this Knowledge section include some simple high level explanation of what Ethereum and the EVM are, rather than deep knowledge content.

For a deep dive, I'd like to add a Wiki format that would be a more manageable setup.

example: https://github.com/ethereum/wiki/wiki

We have SO much content we need to back fill for a detailed read. This is also an opportunity for us to tell our version of the DAO hack and tighten up the story for content outlets like Messari and Wikipedia.

**Comment by TheEnthusiasticAs** [comment]
Yes, I would also put those two there. Could you prepare the content of it for Chris? I would open a new issue specifically for it with refering to #244

**Comment by hitchcott** [comment]
@TheEnthusiasticAs In terms of preparing content, I am probably not the best person for this as I've not been especially involved with ETC until recently.

We sorely need to fill in those gaps in history!  

The DAO is important, but also hard forks, challenges, etc for sure.

Feel free to open another issue, but let's finalise actual content in https://github.com/ethereumclassic/ethereumclassic.github.io/wiki

**Comment by TheEnthusiasticAs** [comment]
I meaned, that @gitr0n1n could prepare (those are not the priority) those contents for you, b/o he is already in topic of researchs. I will open an issue for it. To add them to the website could be done later ;)

**Comment by gitr0n1n** [comment]
https://github.com/ethereumclassic/ethereumclassic.github.io/issues/297

**Comment by gitr0n1n** [comment]
I think these also tie into this page:
https://github.com/ethereumclassic/faq

Similar isssue: https://github.com/ethereumclassic/ethereumclassic.github.io/issues/338

**Comment by gitr0n1n** [comment]
Copying over from https://github.com/ethereumclassic/ethereumclassic.github.io/issues/308

These are blogs, but can still be used as walkthroughs/guides. Some of them don't match to your structure, but maybe there could be added one or two more. These blogs have quality and it will be sad, if they disappear in the blog list - not everyone is going to look their:

https://ethereumclassic.org/blog/2018-03-15-signatures/
https://ethereumclassic.org/blog/2018-03-19-rlp/
https://ethereumclassic.org/blog/2018-01-31-difficulty/
https://ethereumclassic.org/blog/2018-01-26-implicit-info/
https://ethereumclassic.org/blog/2017-12-04-light-clients/
https://ethereumclassic.org/blog/2017-04-28-blocks/
https://ethereumclassic.org/blog/2017-04-18-keys/
https://ethereumclassic.org/blog/2017-03-30-accounts-and-states/
https://ethereumclassic.org/blog/2017-02-28-dns/
https://ethereumclassic.org/blog/2017-02-10-hashes/
https://ethereumclassic.org/blog/2016-12-16-parity/
https://ethereumclassic.org/blog/2016-12-06-why/

**Comment by hitchcott** [comment]
Okay, I'll make sure these get added to the correct sections.

I will figure out a way of duplicating the content and/or linking to the original blog post.

**Comment by TheEnthusiasticAs** [comment]
ok! But pls don't forget to put the author's name and the original used license )

**Comment by hitchcott** [comment]
Yep. I think will probably just link to the original blog article.

**Comment by TheEnthusiasticAs** [comment]
Copied my comment from #308 
"Yes, you are probably right...I saw, you already copy-pasted them to #244. Cool..."

Perhaps, @gitr0n1n, I would not put those links into "_Knowledge Base_" (KB). The KB is for general infos around ETC. The content of links are giving **deeper** knowledges to start to build. 

So, I would like to suggest to move the links to "_3.1 Get Started_"
