### ISSUE TITLE
Use YAML instead of JSON for translation files

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#247]
Ref #206

**Comment by bobsummerwill** [comment]
Great!
So we support both for now?
And maybe can drop MD at some future point if we go through the process of converting all the files?  Mainly the blogs, right?

**Comment by hitchcott** [comment]
Now we support YAML (with markdown) for interface strings and "static" content. For "dynamic" content (namely blog articles), we're using markdown.

I think it's best we keep blog posts in markdown format as there's less to worry about for authors.

**Comment by bobsummerwill** [comment]
Cool - thanks for the info.
