### ISSUE TITLE
Expanded ETC summit section, with agendas, old years, etc.

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#250]
We should copy all of the the old ETC summit content websites into this site, including substructure of pages.

**Comment by bobsummerwill** [comment]
Please don't do anything with this stuff just yet.
I can just add more video and slides from 2019 when I get a chance.

I will want to make a repo for this, when you have this tech stack "whitelabel ready", @hitchcott

**Comment by gitr0n1n** [comment]
Content addressed in:
https://github.com/ethereumclassic/ethereumclassic.github.io/issues/339
