### ISSUE TITLE
Improve blog navigation / pagination / next article, etc.

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#254]
Right now all blog articles are listed in one page, we might want to make this easier to navigate

**Comment by TheEnthusiasticAs** [comment]
For blog navigation: Core Development Updates, General Updates, Education.
Similar to it: 
![image](https://user-images.githubusercontent.com/48069525/69572087-ab961300-0fc3-11ea-8024-49a5cfe914a7.png)
