### ISSUE TITLE
List more dapps (from dappdirect) ?

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#255]

**Comment by gitr0n1n** [comment]
Revamp of the Ecosystem page with relevant 2020 content can be located in the wiki. I crawled the ecosystem this past week. Can we get this information updated on the webpage hitcott? If this is something I can do personally, please feel free to inform me how and I'l get the ball rolling.

https://github.com/ethereumclassic/ethereumclassic.github.io/wiki/Content:-Ecosystem

**Comment by gitr0n1n** [comment]
https://github.com/ethereumclassic/ethereumclassic.github.io/issues/333
