### ISSUE TITLE
Please can we use the Phoenix style guide?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereumclassic/ethereumclassic.github.io#259]
When I initiated the return from WordPress to Github Pages for this site, it was to address the East / West disconnect, and it was to address the poor workflow which we had.

https://bobsummerwill.com/2019/10/03/addressing-east-west-disconnect-in-etc/

@pyskell did awesome work when he commissioned this style guide:

https://github.com/ethereumclassic/phoenix-project

@pyskell did awesome work when he commissioned the new website using that guide:

https://wordpress.ethereumclassic.org/

Please can we apply the Phoenix style guide on this website again?   We have drifted a little as part of the v2 revamp, and 95% of that is good, but the style-drift is not.

Maybe @hitchcott and Don Syang can address this?   Thanks!

For the ETC Coop 2020 governance revamp (and transparency reports, and pending revamp of https://etccooperative.org) we will be matching the style guide too.

@YazzyYaz, Alison and I all dislike the ETC Jigsaw, so we will likely be getting a fresh icon designed in the style of the one created for ETC Summit 2019 which is awesome.

I am also a little unsure on the fonts within that style guide.   I have asked a designed we have Upwork commissioned to make some recommendations on fonts.  We want to have "normal ones" which are not a pain in the arse to have to download.  Just want Google Fonts ones, I think, so I might have a pull-request incoming on that phoenix-project to change the fonts.    We also need an official dark green variant within that style guide, because that bright green is not a good choice when writing documents.

I also personally don't like the plain icons within the style guide, like the "EC" ones.

https://github.com/ethereumclassic/phoenix-project/raw/master/Logo/Logo/PNG/Logo-EC-Color.png

I very much do like the Phoenix and the Fractal:

https://raw.githubusercontent.com/ethereumclassic/phoenix-project/master/Phoenix/Phoenix/PNG/BG/BG-Phoenix-Green-Full.png

https://github.com/ethereumclassic/phoenix-project/raw/master/Logo/Logo/PNG/Logo-Fractal-Color.png

**Comment by bobsummerwill** [comment]
PS.  I love the animation here too.   Would be great if we could replicate that:

https://wordpress.ethereumclassic.org/

**Comment by phyro** [comment]
@bobsummerwill I don't think changing the phoenix repo is a good idea. This was done by a community member with donations from the community and we received it as a packaged style guide and most of us loved it. I'd prefer it if it was preserved and if we need to change the style guide, I suggest we do this it by either forking or creating a new repo. I don't see anything wrong even if we end up having 10 different style guides :+1: 

As for the animation, if you're talking about the logo drawing itself, check this link https://forum.ethereumclassic.org/t/ethereumclassic-org-redesign-and-improvement-in-progress-launch-may-21-2018/1621/33?u=phyro

**Comment by bobsummerwill** [comment]
Sure, @phyro - I can fork it into https://github.com/etccooperative, and make the tweaks there.

But also offer those the community as a pull-request against the original.   And we can talk about whether or not those make sense.

Literally all I am proposing is:

- Adding a darker green color option
- Maybe tweaking the fonts (or not, TBD)

**Comment by bobsummerwill** [comment]
Forked into:
https://github.com/ETCCooperative/phoenix-project

Looks like the changes will just be:

- Adding an entry for the darker green (=existing green, 50% brightness)
- Change title and body fonts (probably to Merriweather and Open Sans)

Likely to commission a new logo for ETC Cooperative as well to replace the jigsaw, but that is outside of the style guide.   Hopefully one in the same style as the one for ETC Summit 2019.

And we just choose NOT to use the "EC" logos within ETC Cooperative, but don't have any alternatives to suggest.

**Comment by hitchcott** [comment]
👍 

Can definitely phoenix things up a bit!

This will be next priority after i18n.

**Comment by bobsummerwill** [comment]
Cheers, mate.

**Comment by TheEnthusiasticAs** [comment]
Hi Jensnbjivbvi   xi j um z.bihvi y Bj  jj BHV
Bmkv bjhug BGB zdhib
Mit freundlichen Grüßen rfhb  Ny
Abdul Aziz Salamvovj  ib  bu h X Ř RFC j

**Comment by hitchcott** [comment]
Might this be an opportunity to have ready to and schedule to release on Phoenix Day?

https://twitter.com/ETCCooperative/status/1221633048120197120

**Comment by bobsummerwill** [comment]
That is a great idea!
Would be good to get things at least ROUGHLY styled that way well ahead of that date, though.
