### ISSUE TITLE
Canonical "best article" on ETC Monetary Policy?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereumclassic/ethereumclassic.github.io#260]
https://twitter.com/BobSummerwill/status/1199510212018757632

Hey OGs,

So the Monetary Policy happened before my time and I don't have great in-depth knowledge of the details.   In particular, it looks like there is not an EXACT hardcap because of the oddities of uncles.

Is there a canonical "best article" explaining the Monetary Policy?   If not then we could really use one, eh, because we are going to get asked this question a lot in the months ahead and want to have our best answer ready to go.

If any OGs are feeling kind, please do join that Twitter thread and help to clarify any questions which might come up.   I don't feel qualified to do much more than share links on that particular topic as of today.   I can "study up" and answer such questions directly in the weeks to come, I am sure.

**Comment by TheEnthusiasticAs** [comment]
dropping here, for the case if someone will seek it again: https://ecips.ethereumclassic.org/ECIPs/ecip-1017

**Comment by TheEnthusiasticAs** [comment]
next time you can put me in  cc

**Comment by gitr0n1n** [comment]
I'd love to get together a nice polished script and have a video explainer built for this monetary policy. it is such a differentiator to ETH, its worth spending some marketing on.

**Comment by gitr0n1n** [comment]
Donald just posted this one https://etherplan.com/2020/02/25/the-ethereum-classic-monetary-policy-explained/10025/
