### ISSUE TITLE
Move v1 to a separate repo and archive

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#266]
I would like to get rid of the unused branches form this repo, namely the v1 source code and builds.

For historical/archiving purposes, I suggest we publish the v1 branches to another repo and archive it (`old-v1-ethereumclassic.github.io` ?).

This will make it less confusing and easy to navigate this repo. I can go ahead and do this if there's no disagreement, but I don't want to create any `ethereumclassic` repos without permission.

Sound okay to you @realcodywburns ?

**Comment by bobsummerwill** [comment]
Thumbs up from me.

**Comment by hitchcott** [comment]
So I've created the new repo: https://github.com/ethereumclassic/ethereumclassic.github.io-v1

Here I've copied over the relevant branches `old-master`, `source-old` and `gh-pages`, and deleted `old-master` and `source-old`.

The one thing I need help with from an admin is to delete the `gh-pages` branch in this repo (https://github.com/ethereumclassic/ethereumclassic.github.io) it's not needed and is protected so I can't delete it myself.

Speaking of admins, who are actually the admins of this repo? 

@realcodywburns

**Comment by bobsummerwill** [comment]
Done, right?

**Comment by hitchcott** [comment]
Not yet, still need an admin to remove the old `gh-pages` branch which is protected.

**Comment by bobsummerwill** [comment]
@realcodywburns ^^ please can you help?
