### ISSUE TITLE
Sign-off english content to be translated

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#267]
Before we accept translations contributions, we should whitelist sections of the English version that are deemed "final" and good enough to be translated into the many other languages. So far the content has not been verified in its entirety by more than one person. Much of the content that was copied over may be out of date, and some content is still pending updates (#261 #235 #260 #244 #241 #186).

In light of this, we can focus on the content that is ready. Please use this thread to confirm which pieces of content on the current staging site content are good enough to be translated. 

https://staging--ethereumclassic.netlify.com/

I will use this thread to reference when implementing #246 and #245.

Only "signed off" content will be shown to translators, and will otherwise not be shown to translators (as it's liable to change and would be a waste of time to translate).

Again, **until content has been signed off in this thread we should not have it translated.**

I await your suggestions on how many people should be required before the content is considered signed off.

**Comment by bobsummerwill** [comment]
Thanks, Chris.
I will try to find time on Sunday to give a final opinion from me on "must do" content fixes.   Perhaps best as a PR actually making changes I think we need.

**Comment by TheEnthusiasticAs** [comment]
The infrastructure and content parts are ok for me. Nothing found since the last time I mentioned points on the etc discord :)

**Comment by hitchcott** [comment]
Presently, this is being managed in the wiki

https://github.com/ethereumclassic/ethereumclassic.github.io/wiki

Contributors, please contribute!

**Comment by gitr0n1n** [comment]
i'm updating the wiki with information gathered on my ecosystem deep dive.

**Comment by hitchcott** [comment]
I'm closing this issue now as we're pretty much wrapped up on english other than news updates.
