### ISSUE TITLE
Pull request for adding ETC ticker to the main page was misunderstood by traders

### ISSUE THREAD

**Issue by ProphetDaniel** [ethereumclassic/ethereumclassic.github.io#27]
After merged pull request for adding [ETC ticker](https://www.cryptonator.com/ui/js/widget/multi_widget.js) functionality, the prices plunged for a while. Maybe it has nothing to do with this, anyway I reverted back main page as soon as possible to avoid the ETC ticker misunderstanding by traders.

What surprised me was the resistance of ETC token prices in face of the increased volatility in prices due to the probable ETC ticker misunderstanding.

<a href="http://imgur.com/Mgpqctl"><img src="http://i.imgur.com/Mgpqctl.png" title="source: imgur.com" /></a>

**Comment by TheOneWhoKnock** [comment]
f**k that i lose my money

**Comment by ProphetDaniel** [comment]
I'm sad to hear that. In the short term, indeed. Keep in mind that Ethereum Classic has shown resilience today, even swinging that percentage too fast it was able to sustain and gradually recover.

We might better protect ourselves from price manipulation from press, website changes, fake stories and so on. Traders need to become more mature and understand this is not an experiment to fade away. It's an organization fulfilled with sound values in which people are commited to the cause with their heart.

**Comment by ProphetDaniel** [comment]
The coincidence of falling prices once ticker was added to the main page didn't happen today.
