### ISSUE TITLE
EN->GER translation: Getting a gatsby.js error 404 with blog "Ethereum Classic Recursive Length Prefix Encoding"

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#284]
![image](https://user-images.githubusercontent.com/48069525/71781746-54c42600-2fd2-11ea-9c97-2e1a755201e8.png)

**Comment by TheEnthusiasticAs** [comment]
solved myself

**Comment by hitchcott** [comment]
@TheEnthusiasticAs was this meant to be repopened?

**Comment by TheEnthusiasticAs** [comment]
Yes, right. There was the same error on another blog. Therefore I reopened. I will close myself, if I see no issues on my side on above mentioned or another blog. I will continue my work this week

**Comment by TheEnthusiasticAs** [comment]
@hitchcott You closed it, b/o it is already fixed for the newer website?

**Comment by hitchcott** [comment]
Yeah, this should be fixed.

https://restructure--ethereumclassic.netlify.com/de/blog/2018-03-19-rlp/

**Comment by TheEnthusiasticAs** [comment]
cool
