### ISSUE TITLE
A license text is missing for blog "The Ethereum Classic Blockchain Is INCOMPLETE & Why That Is OK"

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#285]
@cseberino under which license was this blog? Thx
![image](https://user-images.githubusercontent.com/48069525/71782406-d10e3780-2fd9-11ea-884a-d0a35582ba84.png)

**Comment by cseberino** [comment]
See icon.....CC BY SA
That's a Creative Commons license

**Comment by TheEnthusiasticAs** [comment]
Yes, I know, but in another blogs you used both the icon AND the text. Is only the 'icon' enough?

**Comment by cseberino** [comment]
I don't know.
_______________________________________

Christian Seberino, Ph.D.
Phone: (936) 235-1139
Email: cseberino@gmail.com
_______________________________________

**Comment by bobsummerwill** [comment]
I would suggest adding the text as well, @TheEnthusiasticAs, just to be clear.

**Comment by cseberino** [comment]
" This work is licensed under the Creative Commons Attribution ShareAlike
4.0 International License. "
_______________________________________

Christian Seberino, Ph.D.
Phone: (936) 235-1139
Email: cseberino@gmail.com
_______________________________________

**Comment by TheEnthusiasticAs** [comment]
OK. I will do, tomorrow.

**Comment by hitchcott** [comment]
To save you the trouble of updating every blog article, I can do this for you and add a custom component for this license text that can be included and translated globally.

**Comment by cseberino** [comment]
Please do.
_______________________________________

Christian Seberino, Ph.D.
Phone: (936) 235-1139
Email: cseberino@gmail.com
_______________________________________

**Comment by TheEnthusiasticAs** [comment]
Ok Chris, thx

**Comment by TheEnthusiasticAs** [comment]
Can this issue be closed @hitchcott?

**Comment by hitchcott** [comment]
In hindsight, I think adding the custom component is overkill.

I've added the additional line for this article.

By the way, as per the original commits, those social links don't actually go anywhere.

https://github.com/ethereumclassic/ethereumclassic.github.io-v1/commit/c4ba847d9e834495c2e524c56c27263a294ded92#diff-e6884812f48a82b2820e019a57dfb515R65-R70

@cseberino Do you want me to add links here?
