### ISSUE TITLE
A blog translation could't be saved in the translation tool, german ver. (blog: 2016-08-13-declaration-of-independence)

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#289]
It is an example. The issue could also be with other contents.

**Comment by hitchcott** [comment]
Hi @TheEnthusiasticAs , please can you log out and create a new account? Currently there are no users since the last updgrade

**Comment by hitchcott** [comment]
Please reopen this if you're having problems or ping me in discord.

**Comment by TheEnthusiasticAs** [comment]
Gotcha

**Comment by TheEnthusiasticAs** [comment]
I created a new account - under the same name. I am seeing the languanges, which I allowed to translate, but it is the same problem. Also, it cannot translate from google or show updates on the demo page.

**Comment by TheEnthusiasticAs** [comment]
resolved
