### ISSUE TITLE
The the blog, ger. ver., "2016-08-13-declaration-of-independence" doesn't appear in the demo page

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#291]
It is an example. The issue could also be with other contents.

**Comment by hitchcott** [comment]
Duplicate of #289

**Comment by hitchcott** [comment]
@TheEnthusiasticAs do we need 3 of these issues open? 

We have this one as well as: #290 #289

**Comment by TheEnthusiasticAs** [comment]
I opened 3, b/o those are different occuring issues from my understanding. If you see from a technical point of view, that those are equal, you can close others.

**Comment by hitchcott** [comment]
@TheEnthusiasticAs Can we close these now?

**Comment by TheEnthusiasticAs** [comment]
resolved
