### ISSUE TITLE
Windows support for development mode

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#294]
Some filename (namely images in the blog) contain characters that are unsupported on windows, meaning the project cannot be cloned correctly on Windows.

These should be renamed to remove the unsupported characters.

**Comment by hitchcott** [comment]
I realised that there will be some more tasks than just this to development mode working on windows.

Unfortunately right now this is low priority compared to other updates, so moving to backlog.

Best to use a VM for now; it's pretty easy on windows.

Once I have time I'll install a windows VM and try and get this working.

**Comment by gitr0n1n** [comment]
here are the error logs:
![Untitled](https://user-images.githubusercontent.com/58588775/72962455-a0682500-3d71-11ea-9ef1-6549fbd7faa3.png)
![Untitled](https://user-images.githubusercontent.com/58588775/72962456-a231e880-3d71-11ea-9e64-76958bd5b205.png)

**Comment by gitr0n1n** [comment]
Works!
