### ISSUE TITLE
Remove Newsletter Signup

### ISSUE THREAD

**Issue by stevanlohja** [ethereumclassic/ethereumclassic.github.io#296]
The newsletter signup field needs form validation. See Gif:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10556209/72626225-f0795e80-390f-11ea-91c5-7ad5d15fcc7f.gif)

**Comment by bobsummerwill** [comment]
It actually needs to be killed!

That is a sign-up to an ETC Cooperative run mailing list and has no place on this website.

@hitchcott Please can you kill it with fire?   Thanks!

**Comment by hitchcott** [comment]
Roger
