### ISSUE TITLE
Add the Original source to the "The Manifesto" blog: "A Crypto-Decentralist Manifesto"

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#297]
The original source: https://medium.com/@bit_novosti/a-crypto-decentralist-manifesto-6ba1fa0b9ede#.2m5ro5rr9

**Comment by gitr0n1n** [comment]
Looks like a nice article for the Knowledge center

**Comment by gitr0n1n** [comment]
This would probably be good in a philosophy section with some of Donald's writings.

**Comment by gitr0n1n** [comment]
Added to wiki:

https://github.com/ethereumclassic/wiki/wiki/A-Crypto-Decentralist-Manifesto

**Comment by TheEnthusiasticAs** [comment]
Hey, do you mean in "Learn about Ethereum Classic" (#331) or totally a new page?
