### ISSUE TITLE
Figure out a way to coordinate approvals for PRs

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#302]
At the moment PRs are often left unmerged for a while (for good reason or otherwise). 

It would be great if we could get together some system for more quickly processing them.

I can suggest creating a group in discord just for maintainers on this project so we can ping each other to review and approve PRs.

That being said this might be overkill, and we can just make do with `@`ing the relevant people in the existing channel. Might be better for transparency this way, too.

**Comment by TheEnthusiasticAs** [comment]
There is already the etc_projects channel, where the git notifications are being pushed. There you can ping ppl too. 
But ppl who are subscribed to orga here, get notificated. Some are too long unmerged, maybe because also ppl forget them.

**Comment by bobsummerwill** [comment]
I think it is likely just that the workflow has impeded engagement, but we can get that going now with translators at least and seemingly a few volunteers on content too.   The Kanban should help.   And the Discord channel is as good a place as any to do extra prods for help.   Maybe we can a bot bridge into there which posts GitHub motivations too?
