### ISSUE TITLE
Add an ethereumclassic.org/status page

### ISSUE THREAD

**Issue by bobsummerwill** [ethereumclassic/ethereumclassic.github.io#307]
We should have a canonical "status" page on the ETC website which has pointers to all known status pages, dashboards and general network-health monitors, to avoid the possibility of confusion and false panic, as happened today.

https://twitter.com/el33th4xor/status/1219986686496722945

https://twitter.com/BobSummerwill/status/1220017328546435073

https://twitter.com/BobSummerwill/status/1220059190485372928

https://twitter.com/BobSummerwill/status/1220059807463247874

**Comment by hitchcott** [comment]
There's a whole bunch of these in https://restructure--ethereumclassic.netlify.com/development/network-resources
