### ISSUE TITLE
Content Page: User Guides & Resources

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#308]
We should have a "guides" page on the ETC website which has pointers to vetted guides that support the network. Guides will help build up smaller participants less technical. Similar to what we see in BTC/LN communities. Guides for participants with different motivations: Personal (laptop, desktop, RPi), Professional (Personal Server, Cloud Hosted), Enterprise (Instituational) participants.

- Node guides.
- Mining guides.
- Block Explorer guides.
- Network Status Dashboard guides.

A nice curated onboarding page for people that are interested in support the network but don't know where to start. A place for core developers to showcase their work for network wide adoption.

- How do I host my own wallet?
- How do I spin up an ETC (Mainnet + Testnet) node on a RPi or old laptop?
- How do I spin up a block explorer using the community open source  expedition.dev or blockscout.com?

**Comment by hitchcott** [comment]
Agree, this should be in the knowledge base, I believe.

**Comment by TheEnthusiasticAs** [comment]
I also agree. Yes, the knowledge base is appropriate for it

**Comment by gitr0n1n** [comment]
sitemap: https://ethereumclassic.org/guides

# User Guides & Resources

Insert content

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n 
These are blogs, but can still be used as walkthroughs/guides. Some of them don't match to your structure, but maybe there could be added one or two more. These blogs have quality and it will be sad, if they disappear in the blog list - not everyone is going to look their:

ttps://ethereumclassic.org/blog/2018-03-15-signatures/
https://ethereumclassic.org/blog/2018-03-19-rlp/
https://ethereumclassic.org/blog/2018-01-31-difficulty/
https://ethereumclassic.org/blog/2018-01-26-implicit-info/
https://ethereumclassic.org/blog/2017-12-04-light-clients/
https://ethereumclassic.org/blog/2017-04-28-blocks/
https://ethereumclassic.org/blog/2017-04-18-keys/
https://ethereumclassic.org/blog/2017-03-30-accounts-and-states/
https://ethereumclassic.org/blog/2017-02-28-dns/
https://ethereumclassic.org/blog/2017-02-10-hashes/
https://ethereumclassic.org/blog/2016-12-16-parity/
https://ethereumclassic.org/blog/2016-12-06-why/

**Comment by gitr0n1n** [comment]
From Bob Besu:
https://wiki.hyperledger.org/display/BESU/Building+from+source
https://besu.hyperledger.org/en/stable/
https://pegasys.tech/solutions/hyperledger-besu/

**Comment by TheEnthusiasticAs** [comment]
found this section by Chris Seberino: https://github.com/ethereumclassic/classic-guide

**Comment by gitr0n1n** [comment]
> @gitr0n1n
> These are blogs, but can still be used as walkthroughs/guides. Some of them don't match to your structure, but maybe there could be added one or two more. These blogs have quality and it will be sad, if they disappear in the blog list - not everyone is going to look their:
> 
> https://ethereumclassic.org/blog/2018-03-15-signatures/
> https://ethereumclassic.org/blog/2018-03-19-rlp/
> https://ethereumclassic.org/blog/2018-01-31-difficulty/
> https://ethereumclassic.org/blog/2018-01-26-implicit-info/
> https://ethereumclassic.org/blog/2017-12-04-light-clients/
> https://ethereumclassic.org/blog/2017-04-28-blocks/
> https://ethereumclassic.org/blog/2017-04-18-keys/
> https://ethereumclassic.org/blog/2017-03-30-accounts-and-states/
> https://ethereumclassic.org/blog/2017-02-28-dns/
> https://ethereumclassic.org/blog/2017-02-10-hashes/
> https://ethereumclassic.org/blog/2016-12-16-parity/
> https://ethereumclassic.org/blog/2016-12-06-why/

This looks more like content for the knowledge base. https://github.com/ethereumclassic/ethereumclassic.github.io/issues/244

**Comment by TheEnthusiasticAs** [comment]
Yes, you are probably right...I saw, you already copy-pasted them to #244. Cool...

**Comment by hitchcott** [comment]
Was this supposed to be moved to 'ready' ?

What exactly is the content that should be added to this section?

**Comment by TheEnthusiasticAs** [comment]
As far as I can see, there is only several guides for Besu posted here. So, I am claiming, that it is not 'ready'. ). 

"That list of blog posts looks pretty advanced and seems like it belongs in the developer section.":
So, you are proposing to move it to "_3.1 Get Started_", @hitchcott, instead of to 
_#244_?

I would put "_1.5 User Guides & Resources_" and "_3.1 Get Started_". In essence they are both equal. They are both giving knowledges to build on/with ETC.

**Comment by hitchcott** [comment]
Yeah, fair enough. On second thought, this is fine for section 1.5

I think that as long as we split 1.5 into relevant parts and put the easy stuff first, it'll be good.

**Comment by TheEnthusiasticAs** [comment]
all right

**Comment by gitr0n1n** [comment]
Filling in content: https://github.com/ethereumclassic/ethereumclassic.github.io/issues/390
