### ISSUE TITLE
Create an RSS Feed: ethereumclassic.org/rss

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#310]
Create an RSS feed for popular news aggregators to pull accurate copy from the community.

**Comment by hitchcott** [comment]
Good idea. This is easy with https://www.gatsbyjs.org/packages/gatsby-plugin-feed/

**Comment by TheEnthusiasticAs** [comment]
This issue is open and and labled as done project!?
