### ISSUE TITLE
Content Page: Development Teams

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#317]
sitemap: https://ethereumclassic.org/development-teams

# Development Teams

Ethereum Classic is a decentralized development ecosystem which means there is no 'official' team or formal hierarchy. This global development community is a permissionless 'do-ocracy', where anyone can participate. Individuals and teams choose tasks for themselves and execute them. We collectively establish [rough consensus](https://en.wikipedia.org/wiki/Rough_consensus) through the [Ethereum Classic Improvement Proposal (ECIP)](https://ecips.ethereumclassic.org/) process.

## Development Teams
This is a list of prominent teams that have contributed to Ethereum Classic since the project's genesis block on July 30, 2015. The Ethereum Classic community is appreciative of all protocol level development efforts by individuals, volunteers, and teams.

| Year | Team Name | Twitter | Status | Repository |
| --- |--- | --- | :---: | --- |
| 2015 | [Ethereum Foundation](https://ethereum.org/) | [@ethereum](https://twitter.com/ethereum) | Active | [source code](https://github.com/ethereum/) |
| 2016 | [ETC Consortium](https://etcconsortium.org/) | [@ETCConsortium](https://twitter.com/ETCConsortium) | Active | |
| 2016 | [ETCDEV](https://etcdevteam.com/) | [@getemerald](https://twitter.com/getemerald) | Active | [source code](https://github.com/ETCDEVTeam/) |
| 2016 | [IOHK (Grothendieck)](https://iohk.io/projects/ethereum-classic/) | [@InputOutputHK](https://twitter.com/InputOutputHK) | Inactive | [source code](https://github.com/input-output-hk/mantis) |
| 2016 | [Parity Technologies](https://parity.io/) | [@ParityTech](https://twitter.com/ParityTech) | Active | [source code](https://github.com/paritytech/) |
| 2017 | [ETC Cooperative](https://etccooperative.org/) | [@ETCCooperative](https://twitter.com/ETCCooperative) | Active | [source code](https://github.com/ETCCooperative) |
| 2017 | [Ethereum Commonwealth](https://ethereumcommonwealth.github.io/ethereum-commonwealth-website/) | [@Dexaran](https://twitter.com/Dexaran) | Inactive | [source code](https://github.com/EthereumCommonwealth/) |
| 2018 | [Commonwealth.gg](https://commonwealth.gg) | [@commonwealthgg](https://twitter.com/commonwealthgg) | Active | [source code](https://github.com/p3c-bot) |
| 2018 | [ETC Labs](https://etclabs.org/) | [@etclabs](https://twitter.com/etclabs) | Active | [source code](https://github.com/etclabscore) |
| 2018 | [POA Network](https://www.poa.network/) | [@poanetwork](https://twitter.com/poanetwork) | Active | [source code](https://github.com/poanetwork) |
| 2019 | [ChainSafe](https://chainsafe.io/) | [@ChainSafeth](https://twitter.com/ChainSafeth) | Active | [source code](https://github.com/ChainSafe) |
| 2019 | [ETC Core](https://etccore.io/) | [@etc_core](https://twitter.com/etc_core) | Active | [source code](https://github.com/etclabscore) |
| 2019 | [PegaSys](https://pegasys.tech/) | [@PegaSysEng](https://twitter.com/PegaSysEng) | Active | [source code](https://github.com/hyperledger/besu) |
| 2019 | [Second State](https://www.secondstate.io/) | [@secondstateinc](https://twitter.com/secondstateinc) | Active | [source code](https://github.com/second-state) |
| 2020 | [Gödel Labs 哥德尔实验室](https://www.godel.ai/) | [@Goedellabs](https://twitter.com/Goedellabs) | Active | [source code](https://github.com/multi-geth/multi-geth) |

Note: If attribution is missing for your team, please reach out to the community via the Ethereum Classic [Discord](https://discordapp.com/invite/HW4GckH).

**Comment by gitr0n1n** [comment]
Added PegaSys instead of Hyperledger. Added Parity Technologies.

**Comment by hitchcott** [comment]
I've split this up into two pages.

ECIPs and Development Teams.

Figured they don't both belong under the `teams` header.

**Comment by gitr0n1n** [comment]
Okay the ECIPs section is more a call to action for developers to "Contribute". I agree that it is better to split them.

**Comment by gitr0n1n** [comment]
Split the bottom section to:
https://github.com/ethereumclassic/ethereumclassic.github.io/issues/345

**Comment by gitr0n1n** [comment]
Add:

| 2020 | [Gödel Labs 哥德尔实验室](https://www.godel.ai/) | [@Goedellabs](https://twitter.com/Goedellabs) | Active | [source code](https://github.com/multi-geth/multi-geth) |

**Comment by bobsummerwill** [comment]
@gitr0n1n RE Godel - hurrah!
