### ISSUE TITLE
New Menu Structure

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#323]
Many thanks for your help @gitr0n1n , I am reviewing the content you proposed.

Would it be possible to update the wiki with a high level overview of the menu structure?

I've started populating a list on wiki home page, but I would appreciate if you could update this with your proposal.

**Comment by gitr0n1n** [comment]
# Proposed new content structure
**by @gitr0n1n**

* Ethereum Classic (Note: home/landing page)
* Knowledge
  * What is Ethereum Classic?
  * What is Ether (ETC)?
  * Learn about Ethereum Classic
  * Historic Timeline & Roadmap
  * User Guides & Resources
  * Community Channels
* Use Ethereum Classic
  * Dapps & Protocols
  * Exchanges
  * Wallets
* Development
  * Tutorials
  * Network Resources
  * Development Tools
  * Development Teams
* Media & Press

**Comment by gitr0n1n** [comment]
Added sitemaps to the content pages to align with this structure.

**Comment by TheEnthusiasticAs** [comment]
I would change the "Community Channels" to "Communication Channels" as there are only ETC participants and no community -> centralization

**Comment by gitr0n1n** [comment]
"Social Channels"?

**Comment by gitr0n1n** [comment]
New Structure
Landing Page
Knowledge
MD What is Ethereum Classic?
MD What is Ether (ETC)?
MD Learn about Ethereum Classic
TODO JS Historic Timeline & Roadmap
MD User Guides & Resources
MD Community Channels
Ecosystem JS
Dapps & Protocols
Exchanges
Wallets
Development
MD Get Started
MD Developer Tools
MD Mining Resources
MD Network Resources
MD Development Teams
News JS
Blog
Media
Press
MD ETC Explainers
MD ETC Summit
MD Development Press
MD Press Kit

via https://github.com/ethereumclassic/ethereumclassic.github.io/tree/restructure

**Comment by TheEnthusiasticAs** [comment]
"Social Channel" is also gfm.
Now, I got what you meaned with Press ). thx.

I am ok with this structure.

**Comment by gitr0n1n** [comment]
updated with "Social Channels"

**Comment by gitr0n1n** [comment]
@hitchcott can you change ETC Summit to "Conferences" so we are prepared for ETC videos from other conferences like ETHDenver.

**Comment by hitchcott** [comment]
Restructure branch now has the new menu structure implemented.

One thing I might change is merge the wallets and exchanges into the same page, if the content is sparse.
