### ISSUE TITLE
Add the Multi Asset Wallet ZelCore to the Ecosystem page

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#324]
Multi Asset Wallet ZelCore
https://zel.network/

It has a cool UI

**Comment by milesmanley** [comment]
Thanks @TheEnthusiasticAs - I'll get a PR raised for this 😅

**Comment by milesmanley** [comment]
Hopefully it gets approved - really nice site btw guys

**Comment by TheEnthusiasticAs** [comment]
Linking the PR for it: #325

**Comment by gitr0n1n** [comment]
Addressed in issue 328 

https://github.com/ethereumclassic/ethereumclassic.github.io/issues/328

Closing for housekeeping.
