### ISSUE TITLE
Add the instant exchange operator ChangeNOW & payment processor NOWPayments to the Ecosystem page

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#326]
ChangeNOW 
https://changenow.io

NOWPayments
https://nowpayments.io

**Comment by TheEnthusiasticAs** [comment]
Would be it possible to add it this week? They are going to launch it on Wednesday.

**Comment by hitchcott** [comment]
Sure I can create a PR for the existing version (before restructure is finalised).

**Comment by TheEnthusiasticAs** [comment]
Cool, thank You!
