### ISSUE TITLE
Content Page: Wallets

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#328]
Currently we have "Mobile" and "Desktop" as separate categories.

Obviously some wallets will work on both, but we want to avoid duplicate listings. We should create a third category for these applications called "Mobile and Desktop".

#325

**Comment by gitr0n1n** [comment]
sitemap: https://ethereumclassic.org/wallets

# Ethereum Classic Wallets

### Browser Wallets

- Interactive Browser Wallets: can be used as stand-alone wallets and as interfaces to connect through a web3 wallet or hardware wallet. *Not Recommended:* Keystores & Paper Wallets can be generated from these interfaces.
- Stand-alone Browser Wallets: are dedicated browser wallet with no downloads designed for desktop or mobile use.
- Web3 Wallets: are browser extensions for interacting with DApps built on Ethereum based networks.

| Interactive | Stand-Alone | Web3 |
| :---: | :---: | :---: |
| [MyCrypto](https://www.mycrypto.com) | [Portis](https://www.portis.io/) | [MetaMask](https://metamask.io/) |
| [MyEtherWallet](https://www.myetherwallet.com) | [Squarelink](https://squarelink.com/) | [Nifty Wallet](https://github.com/poanetwork/nifty-wallet) |
|  |  | [Opera](https://www.opera.com/crypto) |
|  |  | [Saturn Wallet](https://www.saturn.network/blog/saturn-wallet-user-manual/) |

### Hardware Wallet

are secure wallets designed for long term storage.

- [Bitski](https://www.bitski.com/)
- [Ledger](https://shop.ledger.com/)
- [SafePal](https://www.safepal.io/)
- [Trezor](https://trezor.io/)

### Software Wallets

for Desktop or Mobile devices.

- [AToken](https://www.atoken.com/)
- [Alpha Wallet](https://alphawallet.com/)
- [Atomic Wallet](https://atomicwallet.io/)
- [Button Wallet](https://buttonwallet.com/)
- [Citowise](https://citowise.com/)
- [Cobo](https://cobo.com/)
- [Coinbase Wallet](https://wallet.coinbase.com/)
- [Coinomi](https://www.coinomi.com/)
- [Cryptonator](https://www.cryptonator.com/)
- [Edge](https://edge.app/)
- [Emerald Wallet](https://emeraldpay.io/)
- [Ethos](https://www.ethos.io/universal-wallet/)
- [Exodus](https://www.exodus.io/)
- [Guarda](https://guarda.co/)
- [Infinito Wallet](https://www.infinitowallet.io/)
- [Jaxx](https://jaxx.io/)
- [Ownbit](https://ownbit.io/)
- [Trust Wallet](https://trustwallet.com/)
- [Zelcore Wallet](https://zel.network/project/zelcore/)

Note: If your wallet is not listed, please reach out to the community via the Ethereum Classic [Discord](https://discordapp.com/invite/HW4GckH).

**Comment by gitr0n1n** [comment]
Addressed issue while revamping the content sections. Using this card to push all the wallet changes.

**Comment by gitr0n1n** [comment]
Added crypto steels since they are an important part of managing your own funds.

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n Could you pls take off the word "capsule" from the description, as they have also other kinds of backup tools. Thx

**Comment by gitr0n1n** [comment]
New wallets added.

**Comment by hitchcott** [comment]
Hi @gitr0n1n I'm going through these updates and noticed that you added some wallets then deleted some (tracking the changes on your comment, you added then deleted BC Wallet, CoolWallet, etc.).

Can you confirm your comment is currently correct?

In future it'll be a lot easier to for me to manage updates like this if you just add each batch of updates as a separate comment (e.g. add X, remove Y). Then I can just replay that series of comments without having to cross-reference the whole list.

**Comment by gitr0n1n** [comment]
I deleted those wallets because they signaled ETC support in the future but don't currently support ETC. @hitchcott
