### ISSUE TITLE
Content Page: What is Ethereum Classic?

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#329]
sitemap: https://ethereumclassic.org/what-is-ethereum-classic

# What is Ethereum Classic?

New to Ethereum Classic? You’re in the right place. Let’s start with the big picture.

**Ethereum Classic is the foundation for a new era of the internet:**
* An internet where money and payments are built in.
* An internet where users can own their data, and your apps don’t spy and steal from you.
* An internet where everyone has access to an open financial system.
* An internet built on neutral, open-access infrastructure, controlled by no company or person.

**Launched on July 30th 2015, Ethereum Classic is the original chain of the Ethereum project.**

At the time of writing, the Ethereum project consists of multiple Ethereum Virtual Machines (or "EVM"), often referred to as "chains".

**The Ethereum project is the world’s leading _programmable_ blockchain project.**

Like other blockchains, Ethereum Classic has a native cryptocurrency called **Ether (ETC)**. ETC is digital money. If you’ve heard of **[Bitcoin](https://bitcoin.org)**, ETC has many of the same features. It is purely digital, and can be sent to anyone anywhere in the world instantly. The supply of ETC isn’t controlled by any government or company - it is decentralized, and it is scarce. You can review ETC's predictable and transparent **[monetary policy](https://ecips.ethereumclassic.org/ECIPs/ecip-1017)**. People all over the world use ETC to make payments, as a store of value, or as collateral. 

**But unlike first generation blockchains, Ethereum Classic can do much more.**

Ethereum Classic is programmable, which means that developers can use it to build new kinds of applications.

These decentralized applications (or “dapps”) gain the benefits of cryptocurrency and blockchain technology. They can be trustworthy, meaning that once they are “uploaded” to Ethereum Classic, they will always run exactly as programmed without any possibility of downtime, censorship, or third party interference; **unstoppable code**. They can control digital assets in order to create new kinds of trust minimizing financial applications. They can be decentralized, meaning that no single entity or person controls them.

**Right now, thousands of developers all over the world are building applications for the greater Ethereum ecosystem, and inventing new kinds of applications, many of which you can use today:**
* Cryptocurrency wallets that let you make cheap, instant payments with ETC or other assets
* Financial applications that let you borrow, lend, or invest your digital assets
* Decentralized markets, that let you trade digital assets, or even trade “predictions” about events in the real world
* Games where you own in-game assets, and can even make real money
* And much, much more.

**The Ethereum project development community is the largest and most active blockchain community in the world.**

It includes core protocol developers, cryptoeconomic researchers, cypherpunks, mining organizations, ETC holders, app developers, ordinary users, anarchists, fortune 500 companies, and, as of now, **you**.

**There is no official company or centralized organization that controls Ethereum Classic.**

Ethereum Classic is an open, permissionless network similar to Bitcoin. Ethereum Classic is maintained and improved over time by a diverse global ETC participants who work on everything from the core protocol to consumer applications. This website, just like the rest of Ethereum Classic, was built - and continues to be built - by a collection of people working together.

**Welcome to Ethereum Classic.**

**Comment by TheEnthusiasticAs** [comment]
I would change the last paragraph to this:
.... Ethereum Classic is maintained and improved over time by a diverse global ETC participants who work ......

**Comment by gitr0n1n** [comment]
Good catch. Agreed. Updated.

**Comment by gitr0n1n** [comment]
i think this is a good first draft that can go live on the website. We don't need to be perfect on copy at this point, we will sharpen our messaging as the project advances. This is a solid foundation to build off of. I think we're good to push this @hitchcott

**Comment by TheEnthusiasticAs** [comment]
yes, we are

**Comment by hitchcott** [comment]
This is just verbatim from https://ethereum.org/what-is-ethereum/ right?

Maybe we should just link to this rather than copying it without attribution...

**Comment by hitchcott** [comment]
For now I have included a reference to this in the `what-is-etc` page.

This is the first part of knowledge base and the very first page for complete new people. I will ensure it's properly summarized. Tomorrow

**Comment by TheEnthusiasticAs** [comment]
thank you!
