### ISSUE TITLE
Content Page: What is Ether (ETC)?

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#330]
sitemap: https://ethereumclassic.org/etc

# What is Ether (ETC)?
ETC is the native currency of Ethereum Classic.

ECIP-1017 created Ethereum Classic's ETC predictable [emission schedule & monetary policy](https://ecips.ethereumclassic.org/ECIPs/ecip-1017).

**This page gives you the basic information you need to get started using ETC.**

↳ What is ETC, and how do I get it?
Ether, or ETC, is Ethereum Classic's native currency. It is "digital money" that can be sent over the internet instantly and cheaply, and also be used in many Ethereum Classic-based applications.

## Purchase ETC
The easiest way to get ETC is to buy some. There are many cryptocurrency exchanges that will allow you to buy ETC, but the one you should use will depend on where you live and how you want to pay.

For more information on where to buy ETC check this non-exhaustive list of [exchanges](https://ethereumclassic.org/exchanges).

## Mining for ETC
More technically advanced users may acquire ETC by allocating computer resources to support the Ethereum Classic network. This method is commonly referred to as "mining" for block rewards. Mining is competitive and requires advanced knowledge that we will not cover here, but here is a list of [mining resources](https://ethereumclassic.org/mining).

**Comment by gitr0n1n** [comment]
# What is Ether (ETC)?
ETC is the native currency of Ethereum Classic.

ECIP-1017 created Ethereum Classic's ETC predictable [emission schedule & monetary policy](https://ecips.ethereumclassic.org/ECIPs/ecip-1017).

**This page gives you the basic information you need to get started using ETC.**

↳ What is ETC, and how do I get it?
Ether, or ETC, is Ethereum Classic's native currency. It is "digital money" that can be sent over the internet instantly and cheaply, and also be used in many Ethereum Classic-based applications.

## Purchase ETC
The easiest way to get ETC is to buy some. There are many cryptocurrency exchanges that will allow you to buy ETC, but the one you should use will depend on where you live and how you want to pay.

For more information on where to buy ETC check this non-exhaustive list of [exchanges](https://ethereumclassic.org/exchanges).

## Mining for ETC
More technically advanced users may acquire ETC by allocating computer resources to support the Ethereum Classic network. This method is commonly referred to as "mining" for block rewards. Mining is competitive and requires advanced knowledge that we will not cover here, but here is a list of [mining resources](https://ethereumclassic.org/mining).

**Comment by TheEnthusiasticAs** [comment]
lgfm
