### ISSUE TITLE
Content Page: Exchanges

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#334]
sitemap: https://ethereumclassic.org/exchanges

### Disclaimer
Use links at your own risk. We try to vet links as best we can, but there is no guarantee that links haven't been tampered with after our initial inspection.

### Centralized Exchanges
- [ABCC](https://abcc.com/en/markets/etcusdt)
- [ACX](https://acx.io/markets/etcaud)
- [Altilly](https://www.altilly.com/market/ETC_USDT)
- [BaseFEX](https://www.basefex.com/trade/ETCUSDT)
- [BCEX](https://www.bcex.ca/trade/etc_usdt)
- [Bequant](https://bequant.io/exchange/ETC-to-USDT)
- [BHEX](https://www.bhex.com/exchange/301/etc/usdt)
- [Bibox](https://www.bibox.com/exchange?coinPair=ETC_USDT)
- [BigONE](https://big.one/trade/ETC-USDT)
- [BiKi](https://www.biki.com/zh_CN/trade/ETC_USDT)
- [Binance](https://www.binance.com/en/trade/ETC_USDT)
- [Binance US](https://www.binance.us/en/trade/ETC_USDT)
- [BitAsset](https://www.bitasset.com/ktrade/ETC-USDT)
- [Bitbns](https://bitbns.com/trade/#/etc)
- [Bitcoin IRA](https://bitcoinira.com/resources/bitcoin-ethereum-price-charts)
- [Bitfinex](https://www.bitfinex.com/t/ETC:USD)
- [BitForex](https://www.bitforex.com/en/spot/etc_usdt)
- [Bithumb](https://www.bithumb.com/trade/order/ETC_KRW)
- [Bithumb Singapore](https://www.bithumbsg.com/exchange/etc-tusd)
- [BitMart](https://www.bitmart.com/trade?symbol=ETC_USDT)
- [BitMax](https://bitmax.io/#/trade/usdt/etc)
- [Bitnaru](https://www.bitnaru.com/exchange)
- [Bitpanda](https://www.bitpanda.com/en/prices/ethereum-classic)
- [BitRabbit](https://bitrabbit.com/markets/etc_btc)
- [Bitrue](https://www.bitrue.com/trade/etc_usdt)
- [Bitsonic](https://bitsonic.co.kr/front/exchange/etc-krw)
- [Bittrex](https://bittrex.com/Market/Index?MarketName=USDT-ETC)
- [Bittrex Global](https://global.bittrex.com/Market/Index?MarketName=USDT-ETC)
- [Bitvavo](https://account.bitvavo.com/markets/ETC-EUR)
- [BitZ](https://www.bit-z.com/exchange/etc_usdt)
- [BKEX](https://www.bkex.com/trade/ETC_USDT)
- [BTC Markets](https://www.btcmarkets.net/buy-sell)
- [BTC Trade UA](https://btc-trade.com.ua/stock/ETC_UAH)
- [BTC Alpha](https://btc-alpha.com/en/exchange/ETC_BTC/)
- [Baobi](https://www.baobi.com/trade?c=ETC%2FUSDT)
- [BW](https://www.bw.com/trade/etc_usdt)
- [C2CX](https://www.c2cx.com/in/trade_usdt_etc)
- [CAT.EX](https://www.catex.io/trading/ETC/USDT)
- [Coinbase Pro](https://pro.coinbase.com/trade/ETC-USD)
- [Coinbene](https://www.coinbene.com/exchange/en_US/ETCUSDT)
- [Coinbit](https://www.coinbit.co.kr/exchange/%C2%B7ETC-KRW)
- [Coindeal](https://frontend.coindeal.com/market/ETC-BTC/)
- [Coineal](https://hk.coineal.com/trade_center.html?s=etc-btc#en_US)
- [CoinEgg](https://trade.coinegg.com/trade/etc_usdt)
- [CoinEx](https://www.coinex.com/exchange?currency=usdt&dest=etc)
- [Coinone](https://coinone.co.kr/exchange/trade/etc/krw)
- [Coinsbit](https://coinsbit.io/trade/ETC_USD)
- [CoinTiger](https://www.cointiger.com/en-us/#/trade_pro?coin=etc_usdt)
- [Coinut](https://coinut.com/spot/ETCUSDT)
- [CPDAX](https://www.cpdax.com/trade/ETC-BTC)
- [Crex24](https://crex24.com/exchange/ETC-BTC)
- [Crypcore](https://crypcore.com)
- [DCoin](https://www.dcoin.com/currencyTrading/ETC_USDT)
- [DEX-Trade](https://dex-trade.com/trading/ETCUSDT)
- [DigiFinex](https://www.digifinex.com/en-ww/trade/USDT/ETC)
- [eToro](https://www.etoro.com/discover/markets/cryptocurrencies/coins)
- [eToroX](https://www.etorox.com/exchange/etc/)
- [EXMO](https://exmo.com/en/trade/ETC_USD)
- [Exrates](https://exrates.me/trading/ETCUSDT)
- [EXX](https://www.exx.com/tradeCoding/eth_usdt)
- [FatBTC](https://www.fatbtc.com/trading?currency=ETC%2FUSDT&freetab=2)
- [Folgory](https://folgory.com/trade-crypto/ETC_USDT)
- [FTX](https://ftx.com/trade/ETC-PERP)
- [Gate](https://www.gate.io/trade/etc_usdt)
- [HitBTC](https://hitbtc.com/ETC-to-USDT)
- [Hoo](https://hoo.com/trade/etc-usdt)
- [HotBit](https://www.hotbit.io/exchange?symbol=ETC_USDT)
- [Huobi Global](https://www.huobi.com/en-us/exchange/etc_usdt/)
- [Huobi Indonesia](https://www.huobi.com.co/exchange/#s=etc_usdt)
- [Huobi Korea](https://www.huobi.co.kr/en-us/exchange/etc_usdt/)
- [Huobi Russia](https://www.huobi.com.ru/exchange/#s=etc_usdt)
- [Independent Reserve](https://www.independentreserve.com/market/etc)
- [Koineks](https://koineks.com/demo/ETCTRY)
- [Korbit](https://www.korbit.co.kr/markets/?market=etc-krw)
- [Kraken](https://trade.kraken.com/markets/kraken/etc/usd)
- [Kucoin](https://www.kucoin.com/trade/ETC-USDT)
- [LiveCoin](https://www.livecoin.net/en/trading/ETC_BTC)
- [MXC](https://www.mxc.com/trade/easy#ETC_USDT)
- [OceanEx](https://oceanex.pro/en/trades/etcusdt)
- [OKCoin](https://www.okcoin.com/spot/trade#product=etc_usd)
- [OKex](https://www.okex.com/market?product=etc_usdt)
- [OKex Koreo](https://okex.co.kr/kr/view/trade/order)
- [Ovis](https://www.ovis.com.tr/)
- [P2PB2B](https://p2pb2b.io/trade/ETC_USDT)
- [Paybito](https://dashboard.paybito.com/view-exchange.html?pair=etc-usd)
- [Poloniex](https://poloniex.com/exchange#usdt_etc)
- [ProBit](https://www.probit.com/app/exchange/ETC-USDT)
- [SouthXchange](https://www.probit.com/app/exchange/ETC-USDT)
- [STEX](https://app.stex.com/en/basic-trade/pair/BTC/ETC/1D)
- [Tokenomy](https://exchange.tokenomy.com/market/ETCBTC)
- [TOKOK](https://www.tokok.com/market?symbol=ETC_USDT)
- [Upbit](https://upbit.com/exchange?code=CRIX.UPBIT.USDT-ETC)
- [VCC Exchange](https://vcc.exchange/exchange/basic?currency=btc&coin=etc)
- [WazirX](https://wazirx.com/exchange/ETC-USDT)
- [WhiteBIT](https://whitebit.com/trade/ETC_BTC)
- [YoBit](https://yobit.net/en/trade/ETC/USD)
- [YunEx](https://yunex.io/trade/etc_usdt)
- [ZB](https://trans.zb.com/etcusdt)
- [ZBG](https://www.zbg.com/trade/etc_usdt)

### Instant Exchanges
*Note:* Instant Exchanges typically offer worse rates than Centralized Exchanges.
- [ABRA](https://www.abra.com/)
- [ALFACashier](https://www.alfacashier.com/)
- [AtomicWallet](https://atomicwallet.io)
- [ChangeAngel](https://www.changeangel.io/)
- [Changelly](https://changelly.com/)
- [ChangeNOW](https://changenow.io/)
- [CoinSwitch](https://coinswitch.co/)
- [Coinveer](https://coinveer.com/)
- [Edge](https://edge.app/)
- [Exodus](https://www.exodus.io/)
- [Exolix](https://exolix.com/)
- [FixedFloat](https://fixedfloat.com/)
- [GoDex](https://godex.io/)
- [Infinito Wallet](https://www.infinitowallet.io/)
- [InstaEx](https://instaex.io/)
- [SimpleSwap](https://simpleswap.io/coins/ethereum-classic)
- [StealthEx](https://stealthex.io/)
- [Swapzone](https://swapzone.io/?to=btc&from=etc)
- [Switchain](https://www.switchain.com)
- [Voyager](https://www.investvoyager.com/blog/how-to-buy-ethereum-classic/)
- [XChange](https://www.xchange.me/)

### Trust Minimizing Exchanges
- [Bisq](https://bisq.network/markets/?currency=etc_btc)
- [EXNCE](https://exnce.com/)
- [Saturn Network](https://www.saturn.network/)

## Payment Processors
- [AnyCoinDirect](https://anycoindirect.eu/en/buy-ethereum-classic)
- [Bit4Sale](https://bit4.sale/)
- [Bitladon](https://www.bitladon.com/ethereum-classic)
- [CoinDirect](https://www.coindirect.com/)
- [CoinGate](https://coingate.com/)
- [Coinmerce](https://coinmerce.io/)
- [CoinPayments](https://www.coinpayments.net/)
- [Cryptomate](https://cryptomate.co.uk/buy-ethereum-classic/)
- [Cryptonator Merchant](https://www.cryptonator.com/merchant/)
- [Fud Desk](https://fuddesk.com/buy-crypto)
- [LiteBit](https://www.litebit.eu/en/buy/ethereumclassic#rate-tile-ethereumclassic)
- [NOWPayments](https://nowpayments.io/)
- [Paxful](https://paxful.com/sell-bitcoin/ethereum-classic-etc)
- [RoundlyX](https://www.roundlyx.com/)
- [Utrust](https://utrust.com/)

Note: If your business is not listed, please reach out to the community via the Ethereum Classic [Discord](https://discordapp.com/invite/HW4GckH).

**Comment by TheEnthusiasticAs** [comment]
We should keep in mind, after updating the page, to include as many exchanges as possible. For the beginning, the Google sheet for etcnodes. Other exchange can then submit PRs.

**Comment by gitr0n1n** [comment]
Added payment processors.

@TheEnthusiasticAs are you sure you want to add EVERY exchange, rather than just the vetted/safer exchanges? I worry about adding an exchange like "CoinTiger" because rumors are out that they're pocketing their customers deposits and not releasing withdrawals. I think we should be careful on who is being listed.

**Comment by TheEnthusiasticAs** [comment]
Yes, ETC is permissionless. So, it should continued everywhere, where it is possible in the ecosystem. There should also be the same warning as on the current one on the newer one @gitr0n1n. That one could be left.

**Comment by gitr0n1n** [comment]
True. Okay if we want a complete list then we have some extra work to do here.

**Comment by gitr0n1n** [comment]
added eToro

**Comment by gitr0n1n** [comment]
Added pricing sources. Changed to be "Notable Exchanges".

**Comment by gitr0n1n** [comment]
To Do: expand the exchange list to be more inclusive.

**Comment by gitr0n1n** [comment]
Pulled all active exchanges from CMC. I need to look at other exchange sources.

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n check this site: https://messari.io/asset/ethereum-classic/exchanges

**Comment by gitr0n1n** [comment]
Messari is a filtered list of vetted exchanges. I think we should cut the list down to that Messari style of list, but you were advocating for ALL exchanges we could find @TheEnthusiasticAs 

I worry about including sketchy un-vetted exchanges on the project website. Here is an example of my concern: https://twitter.com/ccxt_official/status/1202800398664445952?s=20

**Comment by TheEnthusiasticAs** [comment]
Not to sit everyday/month and search for all possible exchanges, there could be put a msg something like this:

As new exchanges appears often on the markets, the update of the list will be made in unregular intervals. 
⚠️ Whilst malicious links are removed as they are discovered, operating with the sprit of permissionless means that there is no guarantee all links are legitimate. Please use with caution and verify for yourself.

**Comment by TheEnthusiasticAs** [comment]
"Messari is a filtered list of vetted exchanges. I think we should cut the list down to that Messari style of list, but you were advocating for ALL exchanges we could find @TheEnthusiasticAs":
Yep, I am taking my link with messari back ).

**Comment by TheEnthusiasticAs** [comment]
To reduce the work on checking the links for their topicality in the future, can there be implimented a link checker script?

**Comment by gitr0n1n** [comment]
Added instant exchanges. Need to search for some more.

**Comment by gitr0n1n** [comment]
Deep dive of instant exchanges is done. Added more

**Comment by gitr0n1n** [comment]
Just did a big update on the lists above @hitchcott . Removed a few exchanges that have gone under/exit scammed (FCoin). Added a bunch in every category.

Addressed in this update: https://github.com/ethereumclassic/ethereumclassic.github.io/pull/354
