### ISSUE TITLE
Content Page: ETC Network News

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#337]
sitemap: https://ethereumclassic.org/etc-network-news

# News

insert content

Set up so we capture Core Dev calls.

ECIP progression news like when an ECIP changes status. Highlight the Simple Summaries and link to formal discussion in github.

Network stat reports like:
https://twitter.com/eth_classic/status/1099914388549570560?s=20
https://twitter.com/ClassicIsComing/status/1227103723941285888?s=20
https://twitter.com/etc_price_/status/1231836499563499520?s=20
https://twitter.com/LunarCRUSH/status/1230871412904099840?s=20

Perhaps we can build this out to model more of Messari's feel:
https://messari.io/asset/ethereum-classic/news

**Comment by gitr0n1n** [comment]
Different from the Development Team news feed. The idea for this news feed is an ETC Network news feed. So ECIPs, core dev calls, hardfork communication, strictly important network related news. NO SPAM.

**Comment by gitr0n1n** [comment]
We want an RSS feed generating from here to send updates to the crypto portfolio companies like:

### Crypto News Aggregators
- [Blockfolio Signal](https://blockfolio.com/signal)
- [Bloomberg Crypto](https://www.bloomberg.com/topics/ethereum-classic)
- [Coinstats News](https://coinstats.app/en/news)
- [CryptoPanic](https://cryptopanic.com/news/ethereum-classic/)
- [Delta Direct](https://delta.app/en/direct)
- [TokenInsight](https://tokeninsight.com/tokenDetail?cid=2659)

**Comment by gitr0n1n** [comment]
if you look at these feeds. some of the are so stale for ETC. We want to post a message on our site saying "Hardofrk at x block" and know that it's pinging people in all of these apps so we don't have to work too manually for information dissemination. But we have to setup the birdges now as they are eroded.

**Comment by TheEnthusiasticAs** [comment]
So, you mean, the messages posted on ETC website will be automatically posted to above mentioned sites? Sure, it is a good idea. And yes, only important posts

**Comment by gitr0n1n** [comment]
> So, you mean, the messages posted on ETC website will be automatically posted to above mentioned sites? Sure, it is a good idea. And yes, only important posts

Yes, Once we have the RSS feed setup. We can reach out to those portfolio monitoring companies and say: "Hey link you news feed up with this so your content is fresh".

Then we will know if we post an article about a hardfork on the website, it'll propagate outward to the big news aggregators where it will be picked up by readers and spread to social media platforms. Meanwhile the dev teams PR people (e.g.: Terry for ETC Labs and Bob for ETCCoop) can reach out to formal news outlets like Coindesk and do their work. But social media people will pick up the news fast and increase sentiment numbers via the news aggregators like cryptopanic

**Comment by gitr0n1n** [comment]
Also this feed will only be ETC Network stuff: ECIP material status changes. Hardfork alerts. Network stats.

Not stuff like "x partners with x to build on ETC!" that can flow throw other avenues. This feed is about network security, not spam.

**Comment by TheEnthusiasticAs** [comment]
Allright!
So, what do "we" need to provide them? I can get in touch with them and provide those data.

**Comment by bobsummerwill** [comment]
This is of high value.
And yes, not partnerships, not product announcements, not “ETC listed on XXX exchange.   This would be protocol updates, or “go live” of substantial infrastructure projects of interest to every developer (Gitcoin, ETCNodes.org, LLVM-EVM, MakerDAO, Connext).

**Comment by gitr0n1n** [comment]
Delta Direct is hooked up to the RSS feed.

**Comment by gitr0n1n** [comment]
> Different from the Development Team news feed. The idea for this news feed is an ETC Network news feed. So ECIPs, core dev calls, hardfork communication, strictly important network related news. NO SPAM.

I think we ended up addressing this with blog posts. We have a special RSS feed just for those posts.

**Comment by gitr0n1n** [comment]
> if you look at these feeds. some of the are so stale for ETC. We want to post a message on our site saying "Hardofrk at x block" and know that it's pinging people in all of these apps so we don't have to work too manually for information dissemination. But we have to setup the birdges now as they are eroded.

I believe these feeds got updated to Phoenix HF. At least the bigger ones like Blockfolio and Delta

**Comment by gitr0n1n** [comment]
I'm going to close this as I think this topic has been solved with the blog post RSS feed and the Articles RSS feed, also there is an ALL rss feed for another wanting to link into both of these feeds.
