### ISSUE TITLE
Content Page: ETC Explainers

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#338]
sitemap: https://ethereumclassic.org/explainers

# Ethereum Classic Explainers

Source content: https://github.com/ethereumclassic/faq

**Comment by gitr0n1n** [comment]
BitcoinTalk Explainer: https://youtu.be/wOxwuoJaJXc

**Comment by gitr0n1n** [comment]
Hardfork: https://www.publish0x.com/the-crypto-enthusiast-blog-intro/what-is-ethereum-classic-etc-the-coin-that-got-away-beginner-xkzrzo

**Comment by gitr0n1n** [comment]
Youtube search:
2018 Hard Fork: https://youtu.be/IOuEgLKqqjE
2019 ETC Explained: https://youtu.be/xcenZlBdmzM

**Comment by TheEnthusiasticAs** [comment]
1. _BitcoinTalk Explainer Video:_ drop it, b/o the better Explainer is under point "3."->example
2. _2018 Hard Fork Video:_ It is outdated - the pros/cons
3. _2019 ETC Explained Video:_ They mention IOHK, which is not more true (no more developments). I would drop it too. I would take this one: https://twitter.com/eToroUS/status/1222630596347858944. More neutral and updated

**Comment by gitr0n1n** [comment]
I just updated the FAQ section and added a bunch of explainers.

https://github.com/ethereumclassic/faq

**Comment by hitchcott** [comment]
I've copied this in; named as FAQs for now (we can review on the next pass)
