### ISSUE TITLE
ETC Ticker not responsive

### ISSUE THREAD

**Issue by NDNewell** [ethereumclassic/ethereumclassic.github.io#34]
#The ETC ticker at the top of the page is not responsive design friendly. Removing it from the head of the page and incorporating it into the body somewhere (trading section perhaps?) or implementing flexbox would solve the problem.

At the moment, resizing the window to a smaller size or using mobile causes it to overlap the page title and looks sloppy.

**Comment by Panguexe** [comment]
I also think it should be removed from the head and placed somewhere else.

**Comment by ProphetDaniel** [comment]
Whats the proposal @NDNewell and @Panguexe?

**Comment by NDNewell** [comment]
Let's remove it from the head first of all. I'd also say that perhaps placing it in the footer, deemphasized, and off to the side. This landing page shouldn't be about the price or we're feeding the 'pump-n-dump' conspiracy. It should be an afterthought and not in a prominent position. I can make the changes, but would appreciate if someone else could do it as I'm very busy for the next few days.

**Comment by soundbit** [comment]
@NDNewell We are working on a new version of the website http://webpassion9.xyz/landing
http://webpassion9.xyz/landing/voting.html

**Comment by NDNewell** [comment]
@soundbit Okay. The ticker would still need to be fixed until the new site is up. Will will you be finished @soundbit ?

**Comment by arvicco** [comment]
Refreshed design has responsive ticker.
