### ISSUE TITLE
Content Page: Press Kit

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#341]
sitemap: https://ethereumclassic.org/press-kit

# Press Kit

insert content

**Comment by TheEnthusiasticAs** [comment]
For what should it serve exactly?

**Comment by gitr0n1n** [comment]
This is for the media to have a source of our Brand Assets

https://github.com/ethereumclassic/Media_Kit

**Comment by gitr0n1n** [comment]
Put some work in at https://github.com/ethereumclassic/Media_Kit. Going to look for opportunities in there to add some value and it will funnel up into this page.

**Comment by gitr0n1n** [comment]
Okay, the Media Kit is updated. We should use this page to highlight our main brand assets and then signal to media memebers to comb this /Media_Kit folder for sourcing image content for their articles.

**Comment by gitr0n1n** [comment]
I think this is a good example of a professional looking press kit page:

https://web.getmonero.org/press-kit/

**Comment by gitr0n1n** [comment]
Source content: https://github.com/ethereumclassic/Media_Kit

**Comment by TheEnthusiasticAs** [comment]
great!

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n "I think this is a good example of a professional looking press kit page:"
The structure of that page can always be improved )
