### ISSUE TITLE
Reminder: Let's make en effort with Aztlan Phoenix to get some clean "branded" press out there

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#346]

**Comment by gitr0n1n** [comment]
This is freshly updated with plenty of good content to spliff up branded content.

https://github.com/ethereumclassic/Media_Kit

**Comment by gitr0n1n** [comment]
https://ethereumclassic.org/blog/2020-06-10-phoenix-hard-fork-upgrade

**Comment by gitr0n1n** [comment]
Looks like everyne is using the Media kit where they can now that they know about it.
