### ISSUE TITLE
Content suggestion: `Clients` should have it's own page

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#348]
Clients are relevant to both developers and miners, but right now the content is either duplicated in both pages or linked to from one.

I suggest we create a new `ecosystem/clients` page, where it just lists the clients.

Perhaps we should also add some extra information about what the difference between the clients is; and which one people should use for different purposes?

Thoughts @gitr0n1n @TheEnthusiasticAs ?

**Comment by TheEnthusiasticAs** [comment]
Ok, but it should be careful, that zhere should not be too many clicks till one gets to its goal.

Say, should I gather infos for them or you have already those?

**Comment by hitchcott** [comment]
I've already got something, I'll push an update today and we can go from there.
