### ISSUE TITLE
Updated Design

### ISSUE THREAD

**Issue by dax-classix** [ethereumclassic/ethereumclassic.github.io#35]
Hi guys, I'm not sure who is the main maintainer of this, but under the instruction of bitnovosti I've pushed a new branch https://github.com/ethereumclassic/ethereumclassic.github.io/tree/dax-redesign.

A preview of the site is here https://dax-classix.github.io/etc-web/

The new branch is a refreshed design, as well as a blog section. It uses gatsby to generate static html, which can be copied into `gh-pages`. New blog posts can be added by simply adding a new markdown file in`/pages/blog`.

Open to thoughts and suggestions from here.

**Comment by NDNewell** [comment]
@soundbit was organizing the new site, but it's been taking some time and we're def in need of a face-lift from our placeholder site.

I think this is a great improvement. I've got some free time coming up, so will look at it more closely and suggest iterations.

**Comment by dax-classix** [comment]
Re the logo, there's been a lot of discussion going on in slack (website-design and logo-design). Generally, yeah, it seems that this logo is preferred.

Not sure about the status of soundbit's site.  All I can say is bitnovosti sent me here. At least until soundbit's is completed we can use this I guess. Eventually, we could use both, just his, or just this one. Will his be using `gh-pages`?

**Comment by soundbit** [comment]
@dax-classix @NDNewell @Panguexe @splix @arvicco Till the end of this week we will publish website's code on Github. Right now we are doing some bug testing and implementing charts/metrics functionality. Furhtermore we are developing sub-pages of our site which will be updated soon. http://webpassion9.xyz/landing/ http://webpassion9.xyz/landing/voting.html#

**Comment by soundbit** [comment]
We do not simply landing page, but also laying the functionality for community development

**Comment by splix** [comment]
@soundbit good job!

Btw, there is a incorrect address for ETC donations: `0x0xe9a7e26bf5c05fe3bae272d4c940bd7158611c` (double `0x` in the beginning). Correct is `0xe9a7e26bf5c05fe3bae272d4c940bd7158611c`

**Comment by soundbit** [comment]
@splix Thank you, we know about all the mistakes in content of the update soon

**Comment by dax-classix** [comment]
Recent iterations of the logo:

![Ethereum Classic](https://ipfs.pics/ipfs/QmVzWw9kvKiQF8YMwNifr1ZXQZhbMHZyud3tUXtDYWMAii)

**Comment by soundbit** [comment]
Our plans for the community platform:

Powerful community engine grants countless possibilities: not only can you do the group blogging or private messaging, you can also share your reactions to posts, create custom badges and score reputation of other users. 
Everything you do on the site — has a meaning and brings results. Communication in the crypt world had never been so fun and easy.

**Comment by dax-classix** [comment]
@soundbit please create another issue for discussing your site, so can keep the issues on topic.

Cheers

**Comment by soundbit** [comment]
@dax-classix Good job with the logo/website! should be discussed with your version of the entire community, but there is little decision-making tools, we are working on it

Logotype set
https://drive.google.com/open?id=0B7OHoKGINFDKRW4wSlExQWpWR0U

**Comment by ProphetDaniel** [comment]
Cool @dax-classix. It looks great! Maybe you can make something similar to this part (http://www.ethnews.com/the-basics) to be added to the website being developed by @soundbit .

**Comment by ProphetDaniel** [comment]
Another thing is to place the country flags for different languages like there is in the footer of [CoinTeleprah news](https://cointelegraph.com/news/ethereum-eth-and-etc-price-trends-week-of-august-16th)

**Comment by arvicco** [comment]
@dax-classix's version is great. Truly, it's pushing the limit of what's possible with Github pages. I suggest that we put it on https://ethereumclassic.github.io/ to replace current stub. There are two things missing there though: price ticker and donation gadget. Is it possible to incorporate them into this design easily, @dax-classix ?

**Comment by ProphetDaniel** [comment]
This is JavaScript coding. I'm not an expert for making a pull request on this. Specially because there's risk in the operation. So we need somebody experienced with JavaScript to make the pull request. In my opinion a JavaScript developer should evaluate and approve the pull request first. @dax-classix, would merge directly from your branch [dax-redesign](https://github.com/ethereumclassic/ethereumclassic.github.io/tree/dax-redesign.) work out of the box? Can you give maintenance on that until new site is up and live?

**Comment by dax-classix** [comment]
Hi all, thanks for the feedback.

I've added a price ticker in the latest commit; https://dax-classix.github.io/etc-web/ (refresh if it's cached).

With regards to donate button - where do the donations go? Who decides how those funds are used?

Pages can be easily added to the `dax-redesign` branch @ProphetDaniel; if there is content for a 'the-basics' page, where can I find it?

With regards to internationalisation, this will be a larger update and we should get proper translators.

In terms of building for `gh-pages`, please check the [readme](https://github.com/ethereumclassic/ethereumclassic.github.io/blob/dax-redesign/README.md). I am happy to manage updates, but it should be pretty easy for anyone that's familiar with node.

**Comment by arvicco** [comment]
Ticker looks good now, any objections to merging this as a replacement for current static stub page?

**Comment by NDNewell** [comment]
Do it!

**Comment by dax-classix** [comment]
Before I pull the trigger, does anyone want to add to or improve the blog post?

**Comment by NDNewell** [comment]
@dax-classix if you want to improve the blog post I recommend getting in touch with someone in marketing @chucksq or @carlo on slack. I think either of them would be excited to do a write up.

**Comment by arvicco** [comment]
I think we need to push the updated design now to coincide with London meetup that will lead to higher volume of new requests. If no objections in the next hour, I'm going to merge it.

**Comment by arvicco** [comment]
OK, my update borked the Github page completely. @dax-classix, your input is much appreciated.
