### ISSUE TITLE
Move "ethereumclassic.github.io-v1" into the "Archive"-repo

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#352]
To have more order there:
_The_
https://github.com/ethereumclassic/ethereumclassic.github.io-v1
_into_ 
https://github.com/ethereumclassic/Archive

**Comment by hitchcott** [comment]
Disagree with this as "archive" is too generic. There may be other projects that are archived under the ethereumclassic organisation

**Comment by hitchcott** [comment]
Might need @realcodywburns 's help on this.

**Comment by TheEnthusiasticAs** [comment]
it is on the main page: https://github.com/ethereumclassic

**Comment by hitchcott** [comment]
Closing this here as i've opened an issue on that repo
