### ISSUE TITLE
Add RSS importing & article tagging for external press links

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#357]
To integrating various different sources for content better, revamp the news section to allow importing RSS, tagging content, filtering content, language-tagging content, and exporting multiple RSS feeds based on those tags.

#310 #340 #337

**Comment by hitchcott** [comment]
Implment: https://github.com/philhawksworth/netlify-plugin-fetch-feeds

**Comment by gitr0n1n** [comment]
Media Articles:
- Automated content in via a list of RSS.
--Keyword Filter for RSS: "Ethereum Classic" "ETC" "Ethash"
--Guide to Adding an RSS feeds from third part sites.

- Manually adding Articles
-- Manually submit a PR - DONE. Cureent method.
-- Automate the PR submission process to just a web form.

**Comment by gitr0n1n** [comment]
Media Articles OUT of website:
- ETC website's RSS feed for crypto news aggregators/twitter bots.
--Guide to Adding an RSS feeds from third part sites.

- Build a Bot to repost an article listed on Ethereum Classic site to social media outlets
--Twitter
--Facebook
--Reddit
--WeChat
-- Discord
--other desired channels
-Guide for social channel maintainers to plug these bots into their channels.

**Comment by hitchcott** [comment]
Content tagging was added in the last update.

We need to figure out a workflow for the RSS importing.

RSS exporting is pretty straightforward.

@gitr0n1n how did you envisage the process of importing and deciding which feeds get published?

**Comment by gitr0n1n** [comment]
@hitchcott I was thinking we do this for ETC dedicated new sources so we don't have to manually keep adding:

Example 1: https://medium.com/feed/etc-core

**Comment by hitchcott** [comment]
@gitr0n1n sounds like a good approach

I guess we could automatically add new articles and have the option to blacklist certain links if they aren't appropriate.

Looking at the etc-core RSS, it looks like it even has tags, which we can auto-populate.

Does Etherplan have an RSS feed?

**Comment by gitr0n1n** [comment]
Looks like Ethplan is a wordpress site. So we could ask Donald to install an RSS feed plugin.

**Comment by gitr0n1n** [comment]
Found it:
https://etherplan.com/feed/

**Comment by gitr0n1n** [comment]
I think the manual system is working pretty well at this point and think your concerns about automated input articles could be problematic after monitoring new feeds for the past 3 months. We would end up with a lot of spam in the articles.

I'm going to close this, because:
+ there is a great tagging system for articles
+ the export RSS feeds have been addressed and linked up to news aggregators like blockfolio and delta.
- the pending input feature does NOT seem as beneficial as I originally drafted.

Closing for housekeeping.
