### ISSUE TITLE
Exchange page Changes

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#365]
Change: "Notable Exchanges" to "Non-exhaustive List of Exchanges"

Change:
- "Exchanges are separated into 3 categories; centralized, decentralized, and instant." to "The following exchanges all support Ethereum Classic. They are separated into 3 categories; centralized, trust minimizing, and instant. Please do your own research on the exchange you choose to source Ethereum Classic. Simply being listed on this site does not constitute an endorsement of the exchange's services by the Ethereum Classic project."

Change:
- Centralized Exchanges (Inclusive List) to Centralized Exchanges

https://restructure--ethereumclassic.netlify.com/ecosystem/exchanges

**Comment by gitr0n1n** [comment]
Move: "BTC Alpha" ahead of "BTC Market" to keep things alphabetical.
Typo: "OKex Koreo" to "OKex Korea"

**Comment by hitchcott** [comment]
@gitr0n1n do we need to have the disclaimer text twice? It is already in a banner at the top of every page with external links...

"Please do your own research on the exchange you choose to source Ethereum Classic. Simply being listed on this site does not constitute an endorsement of the exchange's services by the Ethereum Classic project"

I guess the extra warning here is justified as it is extra important with exchanges, so I'll include it for now.

**Comment by gitr0n1n** [comment]
It's up to you as long as its clear. I only say that because I had to remove a couple exchanges from the list that were illiquid like FCoin
