### ISSUE TITLE
Apps Page changes

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#366]
Games- Add:
- [Aqua Bank](https://aqua.xenobank.com/) - In this game you take care about whale. Fish lives in a protected area with other endangered species. Player is supposed to feed the whale using plankton in order to let it grow. Whale also produces oil as it consumes plankton. Oil and whale meat slices are requested at the Port, where they also supply plankton for feeding. Relax by watching fish in the aquarium grow
- [Commonwealth Country](https://commonwealth.gg/country.html) - Generate an immutable new Country based on your ETC Address.

Suggestions: Change the Colors for the top of the boxes. they look like monopoly cards. Also click a item in the legend and it filters the list.

https://restructure--ethereumclassic.netlify.com/ecosystem/apps-and-protocols

**Comment by hitchcott** [comment]
@gitr0n1n noted on the colours - this will be fixed with #259
