### ISSUE TITLE
Social Channel Page Changes

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#367]
Websites sub-section:

Add: "Regional Websites" to separate EthereumClassic.org from the other websites.

**Comment by gitr0n1n** [comment]
Need to add a section for Development Discord channels as they are popping up.
- Clients
- Core Dev discussions

**Comment by sorpaas** [comment]
Core Paper Ethereum Classic discussion channel -- https://discord.io/ethereumclassic

**Comment by gitr0n1n** [comment]
Clients:
- Core Geth - https://discord.gg/5KwEAdZ
- Hyperledger Besu - https://chat.hyperledger.org/
- Multi Geth - https://gitter.im/multi-geth/community
- Open Ethereum - http://discord.io/openethereum

**Comment by gitr0n1n** [comment]
Add Development Social Channels section:

### Development
- Discord: [Commonwealth.gg](https://discord.gg/crjsdJr), [Core Paper](https://discord.io/ethereumclassic), [ETC Core](https://discord.gg/5KwEAdZ), [OpenEthereum](http://discord.io/openethereum), [PAO Network](https://discord.gg/mPJ9zkq)
- Gitter: [Core Geth](https://gitter.im/core-geth/community), [Multi-Geth](https://gitter.im/multi-geth/community), [Open-RPC](https://gitter.im/open-rpc/community), [POA Network](https://gitter.im/poanetwork/)
- Matrix: [ECIPs](https://riot.im/app/#/room/#ecips:matrix.org), [Parity Tech](https://riot.im/app/#/room/#watercooler:matrix.parity.io)
- Rocket Chat: [Hyperledger Besu](https://chat.hyperledger.org/)
- Telegram: [ETCDEV](https://t.me/GetEmerald), [ETC Labs](https://t.me/etclabs), [Parity Tech](https://t.me/parity_technologies), [POA Network](https://t.me/poa_network)
- Weibo: [Gödel Labs](https://weibo.com/godellabs)

**Comment by gitr0n1n** [comment]
Remove: Matrix (Developer) from the chat section

I relocated to the new Developer section under Matrix: ECIPs
