### ISSUE TITLE
Mining Resources

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#368]
Add: Miner Software

[Minergate xFast](https://minergate.com/downloads) (Windows AMD and Linux AMD)

Change: "Text here" to "Below is a non-exhaustive collection of mining resources developed for Ethereum Classic. If you have questions, there is an active #Mining channel in the Ethereum Classic Discord."
https://restructure--ethereumclassic.netlify.com/development/mining-resources/

**Comment by TheEnthusiasticAs** [comment]
... Ethereum Classic mining Participants.

**Comment by gitr0n1n** [comment]
> ... Ethereum Classic mining Participants.

good catch. edited.
