### ISSUE TITLE
Press pages changes

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#371]
Here is a good base look:
https://web.getmonero.org/press-kit/

https://restructure--ethereumclassic.netlify.com/press

**Comment by hitchcott** [comment]
@gitr0n1n - what is the difference between this page and the Media Kit page ? 

I was planning to just use the same menu structure overview for https://restructure--ethereumclassic.netlify.com/press/ (just adding a small description consistent with other sections)

**Comment by gitr0n1n** [comment]
Maybe the Press not nested, but the Conference nested

**Comment by gitr0n1n** [comment]
So /press = media_kit.

We don't have to name it media kit on the website.

**Comment by hitchcott** [comment]
To keep things simple for now and to allow for future expansion, i've kept the same structure as the other pages.
