### ISSUE TITLE
Clients page changes

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#372]
Update All clients. New names, and support/chat channels.

## Ethereum Classic Network Clients

| Client Name | Status | Repository | Support |
| --- | ---| --- | --- |
| [Core-Geth](https://github.com/etclabscore/core-geth) | Maintained | [releases](https://github.com/etclabscore/core-geth/releases) | [gitter](https://gitter.im/core-geth/community) |
| [Hyperledger Besu](https://besu.hyperledger.org/) | Maintained | [releases](https://github.com/hyperledger/besu/releases) | [rocket chat](https://chat.hyperledger.org/) |
| [Multi-Geth](https://github.com/multi-geth) | Maintained | [releases](https://github.com/multi-geth/multi-geth/releases) | [gitter](https://gitter.im/multi-geth/community) |
| [OpenEthereum](https://github.com/openethereum) | Maintained | [releases](https://github.com/openethereum/openethereum/releases) | [discord](http://discord.io/openethereum) |

https://restructure--ethereumclassic.netlify.com/development/clients/

**Comment by TheEnthusiasticAs** [comment]
The MultiGeth got "Add Phoenix hard fork support for Kotti and Mordor". Let's see how the result will be. The Status: Development

**Comment by gitr0n1n** [comment]
> The MultiGeth got "Add Phoenix hard fork support for Kotti and Mordor". Let's see how the result will be. The Status: Development

Spoke with Sopraas, I removed the recommended and what not. He assured me the client will have continued support. So nothing to worry about.

**Comment by gitr0n1n** [comment]
Added links to the support channels for these clients to help funnel users to the right area
