### ISSUE TITLE
Theory page changes

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#373]
Change:
"To help you understand why ETC exists and what it stands for, this section contains a selection of articles focused on ETC philosophy."
to
"Ethereum Classic maintains the original, unaltered history of the Ethereum network. The Ethereum project's mainnet initially released via Frontier on 30 July 2015. However, due to a hack of a third-party project, the Ethereum Foundation created a new version of the Ethereum mainnet on 20 July 2016 with an irregular state change implemented that erased The DAO theft from the Ethereum blockchain history. The Ethereum Foundation applied their trademark to the new, altered version of the Ethereum blockchain; Ethereum (ticker: ETH). The older, unaltered version of Ethereum was renamed and continued on as Ethereum Classic (ticker: ETC).

This section of the Ethereum Classic website contains articles focused on the philosophy that keeps the immutable, original version of the Ethereum network running."

Add:
- [What is Ethereum Classic (ETC)?](https://www.publish0x.com/the-crypto-enthusiast-blog-intro/what-is-ethereum-classic-etc-the-coin-that-got-away-beginner-xkzrzo) - A Beginner's Guide to the `The Coin that Got Away`
- [Phyro's Recap of ETC History](https://phyro.github.io/etc-history/)
- [Into the Ether with Ethereum Classic](https://grayscale.co/insights/into-the-ether-with-ethereum-classic/) - The Store of Value Commodity to Power the Internet of Things
- [Ethereum Classic Principles](https://etherplan.com/2019/08/14/ethereum-classic-principles/8575/)
- [Ethereum Classic Opportunities](https://etherplan.com/2019/08/14/ethereum-classic-opportunities/8614/)
- [How to Have a Vision for Ethereum Classic Without Creating a Governance Orgy](https://etherplan.com/2019/07/22/how-to-have-a-vision-for-ethereum-classic-without-creating-a-governance-orgy/8359/)
- [The Ethereum Classic vs Ethereum 1.x Dichotomy](https://etherplan.com/2019/09/18/the-ethereum-classic-vs-ethereum-1-x-dichotomy/8752/)

https://restructure--ethereumclassic.netlify.com/knowledge/theory/

**Comment by TheEnthusiasticAs** [comment]
Individual blogs - **educational** are ok, like by phyro - AND articles should not be included into the website (spamming). In this context, I would not take the article by coindesk. But several topics about "what is ETC", is also too much...

Actually, the blogs by etherplan for the last ~2y can be taken as those are educational.

**Comment by gitr0n1n** [comment]
I'm fine with you editing out anything you don't see ass applicable. Just triyng to aggregate the content in here to have it plished up by people like you @TheEnthusiasticAs

**Comment by gitr0n1n** [comment]
NEW SECTION- OPTIONAL ADD. NEEDS CONSIDERATION.
Ethereum Tech Stack Theory
### The Ethereum project and greater EVM ecosystem
- [The idea of Smart Contracts](https://web.archive.org/web/20020316215014/http://szabo.best.vwh.net/idea.html) - Nick Szabo's idea of smart contracts post from 1997.
- [Bitcoin: A Peer-to-Peer Electronic Cash System](https://bitcoin.org/en/bitcoin-paper) - Satoshi Nakamoto's original paper is still recommended reading for anyone studying how Bitcoin works.
- [Making Smart Contracts Smarter](https://eprint.iacr.org/2016/633.pdf) - Smart contract security attacks.
- [Ethereum Classic (ETC) Wiki Philosophy](https://github.com/ethereumclassic/wiki/Philosophy) - Some of the core philosophies of Ethereum's ETC chain.
- [Ethereum Classic (ETC) Improvement Proposals](https://ecips.ethereumclassic.org/) - Standards for the Ethereum's ETC platform, including core protocol specifications, client APIs, and contract standards (ECIPs).
- [Ethereum (ETH) Wiki Philosophy](https://github.com/ethereum/wiki/Philosophy) - Some of the core philosophies of Ethereum's ETH chain.
- [Ethereum(ETH) )Improvement Proposals](https://eips.ethereum.org/) - Standards for Ethereum's ETH platform, including core protocol specifications, client APIs, and contract standards (EIPS).

**Comment by TheEnthusiasticAs** [comment]
ok. I will see, that I will gather the applycable etherplan's blogs to ETC website on this weekend.
