### ISSUE TITLE
Roadmap page changes

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#374]
Change:
"A brief history of the events that created and defined Ethereum Classic."
to 
"A historical account of the events that created and defined Ethereum Classic."

Future Roadmap sections
Add:
Q1: 5M20 Era 3 Block Reward reduction.
Q1: Cancel Aztlan. Respec Phoenix Upgrade. Same block for ETH Istanbul Parity goal.
Q1: Clients Implement Phoenix Upgrade at hard Date listed below.
Q1: March: Phoenix Live on Testnets. Testing begins. Several Known Issues to Solve. A Challenging Upgrade. A complex upgrade, so development teams are allocating resources to deep testing. Always a potential for a delay with a complex upgrade. ETC will never rush to upgrade the mainnet, security is priority over speed.
Q1: Status Codes: ECIP-1050 moves to Final status.
Q1: Website 2020 Upgrade by hitchcott
Q2: Establish Systemic, Automated Communication Lines to the Gen. Public outlets: News Aggregators, Twitter Posts, Mining Pools. Need clear protocol lines of communication for network security. Not for promotional material.
Q2: Improve Documentation
Q2: Build ETC Specific Guides.
Q2: Phoenix Upgrade Backward Compatibility Testing.
Q2: Phoenix Upgrade Gas Vulnerability Testing
Q2: Account Versioning Review. Potential
Q2: GitCoin Crowdfunding Native ETC
Q3: Long-term Development Resources Discussion: Public Good Network Protocols, Fund Disbursement Methods, DAO fund allocation.
Q3: Updates to ECIP process via ECIP-0001
Q3: Account Versioning
Q3: Astor Testnet tests/results
Q3: Gas Range Discussion: Upper and Lower Bounds
Q4: Mining Algorithm Discussion: Astor SHA3 Change, DAG reduction, No Change, 
Q4: Interoperability Projects: Port over ETH network protocols. Build ETH<>ETC bridges.
Q4: FlyClients Discussion
Q4: Interoperability Market Capture. ETC added to more products increase access/utility for ETC.

https://restructure--ethereumclassic.netlify.com/knowledge/roadmap

**Comment by gitr0n1n** [comment]
Hard dates:

Phoenix Testnet Implementation Dates:
Core-Geth Implemented on March 4, 2020
Hyperledger Besu on March 9, 2020
Multi-Geth March 9, 2020
OpenEthereum still pending.

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n do you also have the block numbers for them? I want to add those testnets to subreddit banner. Thx

**Comment by bobsummerwill** [comment]
https://ecips.ethereumclassic.org/ECIPs/ecip-1088

999_983 on Mordor Classic PoW-testnet (April, 2020)
2_200_013 on Kotti Classic PoA-testnet (April, 2020)
10_500_839 on Ethereum Classic PoW-mainnet (June 10th, 2020)

Those “April” estimates obviously off.

**Comment by TheEnthusiasticAs** [comment]
Aaah.. the tests were started at/on the same time/block on several clients!?! OK.
