### ISSUE TITLE
Developement Teams page changes

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#375]
Add Team:

| Year | Team Name | Twitter | Status | Repository |
| --- |--- | --- | :---: | --- |
| 2017 | [Core Paper](https://corepaper.org/) | [@corepaper](https://twitter.com/corepaper) | Active | [source code](https://github.com/corepaper/corepaper) |

**Comment by gitr0n1n** [comment]
This is Wei's attribution. I'm not sure if there are any other independant developers that would like their atrribution. @TheEnthusiasticAs

**Comment by TheEnthusiasticAs** [comment]
I also don't know, except him.

**Comment by gitr0n1n** [comment]
Okay phyro hit me up with these OG's that could use attribution:
gravity, elaine, cody

@phyro can you give us some details on them so I can either reach out or give temp attribution

year, company/handle, active/inactive?

I tihnk Cody is covered by ETC Coop, but maybe he wants his own attribution for his company since he's been around since pre-fork.
