### ISSUE TITLE
Apps and Protocols: Rerange and concentrate on the clicked topic. To show all, there would be the "All" button

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#376]
![image](https://user-images.githubusercontent.com/48069525/76655695-20d72500-656e-11ea-85f1-48a33d44c2df.png)

**Comment by gitr0n1n** [comment]
Change:
"Ethereum Classic hosts a growing collection of (decentralized) applications and protocols. This page is an overview of the state of the ETC dapposphere."
to
"Ethereum Classic hosts a growing collection of decentralized applications and protocols. This page is an overview of the state of the ETC network development.

In 2020 ETC<>ETH achieved network parity, which allows development teams to easily add Ethereum Classic to their projects.  We expect this list to grow in the coming years as development teams learn about Ethereum Classic's unique properties like: ETC's monetary policy, the network's commitments to backwards compatibility for their mainnet contracts, and a predictable emission schedule for the network's miners."

**Comment by gitr0n1n** [comment]
Can thse cards be collapsable so the name shows and when you click it the card opens up with a description? That might make this more manageable when this list grows to 200 dapps

**Comment by hitchcott** [comment]
@gitr0n1n Yes, once we get more items we can review that. I'll create a separate issue for that.
