### ISSUE TITLE
Add Forks Diagram

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/ethereumclassic.github.io#378]
The existing restructure lists the ETC forks.

It would be cool to have something like this https://consensus.corepaper.org/wiki/Ethereum_family

**Comment by gitr0n1n** [comment]
Totally agree. If you can make it interactive with some js, that would be super fresh!

**Comment by gitr0n1n** [comment]
Name | Release date | Release block
-- | -- | --
Frontier | 2015-07-30 | 0
Frontier Thawing | 2015-09-08 | 200,000
Homestead | 2016-03-15 | 1,150,000
The DAO Bailout | 2016-07-20 | 1,920,000
Gas Reprice | 2016-10-24 | 2,500,000
Diehard | 2017-01-13 | 3,000,000
Gotham (5M20 Era 2) | 2017-12-11 | 5,000,000
Defuse Difficulty Bomb | 2018-05-29 | 5,900,000
Atlantis | 2019-07-29 | 8,500,000
Agharta | 2020-01-11 | 9,573,000
Gotham (5M20 Era 3) | 2020-03-17~ | 10,000,000
