### ISSUE TITLE
Suggestion: Move `Teams` to ecosystem?

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#379]
Although dev related, it's not really interesting for developers to learn. I think it should go into ecosystem to show that there are developers in the ecosystem.

**Comment by TheEnthusiasticAs** [comment]
The sequence is: Ecosystem -> Teams (contributors) -> Developers ->Developer Documentations. 
To make it easy to find, the Developer's category was moved to the foreground. But this category should still be available under "Ecosystem". So, if you have the same structure in mind, then my answer is "Yes, do it" ).

The Ecosystem is the generic term for all.
