### ISSUE TITLE
ETC Page review

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#386]
Change:
"Ethereum Classic aka ETC aka has a number of meanings depending on usage:

- Broadly, ETC refers to the Ethereum Classic Network, including the blockchain itself and the wider ecosystem and community

- ETC also refers to the native currency, or base token of the Ethereum Classic Blockchain, commonly traded under the ETC ticker symbol on exchanges

- In a technical context, ETC is also known as Ether or Wei"

to

"Ethereum Classic nomenclature:

- **"Ethereum Classic"** - Ethereum Classic is an open source, blockchain-based distributed computing platform featuring smart contract (scripting) functionality. It supports a modified version of Nakamoto consensus via transaction-based state transitions executed on a public Ethereum Virtual Machine (EVM). The Ethereum Classic network consists of developers, miners, businesses, and end user.

- **"Ether"** -  Ethereum Classic's native Ether token is a cryptocurrency traded on digital currency exchanges under the ticker symbol ETC. Ether is created as a reward to network nodes for a process known as mining, which validates computations performed on Ethereum Classic's EVM.

- **"Gas"** - Gas, an internal transaction pricing mechanism, is used to mitigate spam and allocate resources on the network.

https://deploy-preview-351--ethereumclassic.netlify.com/knowledge/what-is-etc/

**Comment by gitr0n1n** [comment]
Change:

"ETC is "digital money" that can be sent over the internet instantly and cheaply, and also be used in Ethereum Classic applications."

to

"Ethereum Classic Monetary Policy:
On 11 December 2017, the total supply of Ether (ETC) on Ethereum Classic was hard capped at 210,700,000 ETC via the Gotham hard fork upgrade. This added a Bitcoin inspired deflationary emission schedule that is documented in Ethereum Classic Improvement Proposal (ECIP) 1017. The emission schedule, also known as 5M20, reduces the block reward by 20% every 5,000,000 blocks. Socially, this block reward reduction event has taken the moniker of "The Fifthening."

Date | 5M20 Era | Block | Block Reward | Total Era Emission
-- | -- | -- | -- | --
2015-07-30 | Era 1 | 1 | 5 ETC | 25,000,000 ETC
2017-12-11 | Era 2 | 5,000,001 | 4 ETC | 20,000,000 ETC
2020-03-17 | Era 3 | 10,000,001 | 3.2 ETC | 16,000,000 ETC
2022-04-15 | Era 4 | 15,000,001 | 2.56 ETC | 12,800,000 ETC
2024-05-07 | Era 5 | 20,000,001 | 2.048 ETC | 10,240,000 ETC

**Comment by hitchcott** [comment]
@gitr0n1n it seems that the chart isn't strictly correct as it does not include the uncle reward
