### ISSUE TITLE
Teams page review

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#397]
Add:
| 2019 | [Code Shelter](https://www.codeshelter.co/) | [@code_shelter](https://twitter.com/code_shelter) | Active | [source code](https://github.com/multi-geth/multi-geth) |

Change Gödel Labs Entry to:
| 2020 | [Gödel Labs 哥德尔实验室](https://www.godel.ai/) | [@Goedellabs](https://twitter.com/Goedellabs) | Active | [source code](https://github.com/multi-geth/multi-geth) |

https://deploy-preview-351--ethereumclassic.netlify.com/ecosystem/teams

**Comment by hitchcott** [comment]
Added, can I confirm the coldshelter github is multigeth?
