### ISSUE TITLE
The red notification banner about upcoming updates/upgrades is missing on the website

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#408]

**Comment by hitchcott** [comment]
It's currently hidden. If we re-enable it, what should it say?

**Comment by bobsummerwill** [comment]
It would probably be good to re-enable it for Phoenix.

We can point to https://etcnodes.org/phoenix for now.    And later switch to a https://ethereumclassic.org/phoenix page.

**Comment by gitr0n1n** [comment]
@hitchcott I think it would be great to have a note similar to what's on the phoenix redesign and a redirect to the clients page:
"HARD FORK ALERT
Ethereum Classic's "Phoenix" upgrade is planned for June, 2020 on block 10,500,839. If you run a node, please upgrade to a compatible client.
Upgrade Button target: https://ethereumclassic.org/development/clients

https://phoenix-branding--ethereumclassic.netlify.com/

**Comment by gitr0n1n** [comment]
Live on website.

https://github.com/ethereumclassic/ethereumclassic.github.io/pull/424
