### ISSUE TITLE
Add a note for article submissions on the website

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#409]
To avoid an unnesssary work, I would put a msg here something like:
![image](https://user-images.githubusercontent.com/48069525/77850887-c973be80-71d5-11ea-9bad-e42e2bbca12a.png)

"To reduce spamming, pls submit articles, which have a technical nature, e. g. a "Walkthrough of installing a client", "Technical tipps", The summary of the last Developer Call", etcetera. Before you start to write, pls check here, whether there is already a similar one."

**Comment by gitr0n1n** [comment]
I added this change to my current PR. It is address and this issue can be closed, assuming I edited the document correctly. @TheEnthusiasticAs

**Comment by TheEnthusiasticAs** [comment]
:))
