### ISSUE TITLE
Add the blog posts from etherplan.com, which are ETC/Blockchain related

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#410]
Please copy-paste the content from https://etherplan.com/ with the refer to the etherplan/Donald McIntyre (author, link) to ETC website - section "Blog Articles". This issue here should stay always open, as the content created on etherplan, happens periodically. 

The Assignee(s) is/(are) everyone,

**Comment by gitr0n1n** [comment]
These are added into the "Media" articles sections where all 3rd party content will reside. I've pulled in his docs in my PR. This Issue can be closed.

https://github.com/ethereumclassic/ethereumclassic.github.io/pull/414
