### ISSUE TITLE
Media page changes

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#418]
Work
- Clean up current content.
- Backfill old content to bring the page to current date.
- Build Guide so the general public can submit their own ETC related content.
- Draft guidelines on what's not recommended in terms of content.
Done in PR.

ADD: DATE FILTER

https://ethereumclassic.org/news/media

**Comment by gitr0n1n** [comment]
Clean up conetent. Back fill in some articles for teams.
Merged to dev branch.
https://github.com/ethereumclassic/ethereumclassic.github.io/pull/414

**Comment by gitr0n1n** [comment]
Backfilling in random content like walk throughs tutorials, ETC investment trust, and other missing coverage.

Not merged yet, work in progress:
https://github.com/ethereumclassic/ethereumclassic.github.io/pull/415

**Comment by gitr0n1n** [comment]
Clean up current content.
- DONE
Backfill old content to bring the page to current date.
 - DONE.
No ETC Coop articles since they're in limbo. They can back fill with the new guide.

Build Guide so the general public can submit their own ETC related content. 
- DONE

Draft guidelines on what's not recommended in terms of content.
- DONE

**Comment by gitr0n1n** [comment]
ADD: DATE FILTER

I added a bunch...

**Comment by gitr0n1n** [comment]
NEEDS: Date Filter. I'm thinking something similar to the Apps page.

| 2015 | 2016 | 2017 | 2018 | 2019 | 2020 |

Also noticed that the dates are listed 1 day dehind the article's actual post date for some reason.

**Comment by hitchcott** [comment]
@gitr0n1n this is probably because of the server time settings on the build server (timezone difference), i'll see what I can do

**Comment by hitchcott** [comment]
@gitr0n1n is this closable with the latest update #452 ?

**Comment by gitr0n1n** [comment]
Yes, thanks!
