### ISSUE TITLE
Other Blockchain Explorers + Twitter Accounts

### ISSUE THREAD

**Issue by dax-classix** [ethereumclassic/ethereumclassic.github.io#42]
In the interests of community widening it would make sense to add a dropdown for the blockchain explorers, instead of just having one link. 

I can see these from reddit:

etherhub.io
gastracker.io
etherx.com
etcchain.com

Any others that are missing?

Similarly, I think it makes sense to add ethereumclassic as well as eth_classic twitter.

Approve?

**Comment by arvicco** [comment]
Sure. The more resources, the merrier. ;)
