### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by arvicco** [ethereumclassic/ethereumclassic.github.io#43]
Since I couldn't find a way to modify html, here is the list of proposed changes:

a security audit is compelted by Dejavu -> a security audit is *completed* by Dejavu
citing many game-theoritcal security issues -> citing many game-*theoretical* security issues
The only reamining option is a controversial Hard Fork. -> The only *remaining* option is a controversial Hard Fork.
consensus is declaired and an updated client is released -> consensus is *declared* and an updated client is released
champangne corks are popped all over the globe -> *champagne* corks are popped all over the globe (edited)
many are surpised to find that miners continue mining blocks -> many are *surprised* to find that miners continue mining blocks
economically-charged vitriolic spats being to take hold of the community -> economically-charged vitriolic spats *begin* to take hold of the community
begins to branch off from the forked-chain subreddits and form it's own communication channels -> begins to branch off from the forked-chain subreddits and form *its* own communication channels
The Etherum Classic community begins to rally behind a stabailizng ETC price -> The Etherum Classic community begins to rally behind a *stabilizing* ETC price
new ideas being to surface -> new ideas *begin* to surface
Seperate your ETH/ETC -> *Separate* your ETH/ETC
safe despite the newly-discoverd critical security flaw -> safe despite the newly-*discovered* critical security flaw
The community lets out a sigh of releif -> The community lets out a sigh of *relief*
Flame wars begin in the once peacful  -> Flame wars begin in the once *peaceful*

**Comment by dax-classix** [comment]
Thanks for the updates.

I am ready to go with the new deploy script so anyone can make changes without having to rebuild the html. Do you know who is an owner of this repository? They need to allow the Travis CI request and create a deploy key for this repo.

**Comment by dax-classix** [comment]
I am told Travis has been accepted, just need the deploy key added (please PM bitnovosti or me on slack)

**Comment by dax-classix** [comment]
@arvicco okay, those typos are sorted out. I should really install a spellchecker in my code editor.

I have also updated the readme explaining how the new build system works. Let me know if you have any questions / issues. You can follow builds progressing here: https://travis-ci.org/ethereumclassic/ethereumclassic.github.io

**Comment by arvicco** [comment]
@dax-classix Thanks a lot! I'll try to test the content management process (as outlined in a Readme) tomorrow and I'll let you know how it went.
