### ISSUE TITLE
Fractoral ETC Logo in the BG

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#437]
I see this was added on the landing page.

Can you add this design element to all of the other pages with large grey backgrounds?

Example: https://ethereumclassic.org/knowledge

**Comment by hitchcott** [comment]
Personally, I don't think is going to add much value and will interfere with the content.

If you can find a modern example of people doing this then perhaps I can recreate that, but I don't think it's common practice.

**Comment by gitr0n1n** [comment]
sounds good, you're the designer.
