### ISSUE TITLE
Add yaz's ETC guide to porting page

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#441]
https://medium.com/ethereum-classic/kotti-solidity-etc-oh-my-2ae36926454d

**Comment by hitchcott** [comment]
Is this still relevant with the latest hard forks?

**Comment by gitr0n1n** [comment]
I added to the articles section. I think its helpful for explaining version controling your solidity. But its dated. it would be great to get an update for Phoenix.

**Comment by gitr0n1n** [comment]
while dated, i think its a helpful guide for isolating code to specific hardforks and thir capabilities.

**Comment by gitr0n1n** [comment]
Added to the "Guides" Turorial section page
