### ISSUE TITLE
Restructuring of news / press

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#445]
Update: the recent PR #452 has solved half of this issue.

Still need to update the press section and rename existing routes.

---

We will be adding two new sections:

- Conferences, which will be split into multiple pages rather than one
- Podcasts, which will show a list of videos of podcasts etc.

We are already using `media` for the 'external links under news' section, so we might want to rename our routes to the following: 

- News
  - news/ *(blogs + press)*
  - news/blog
  - news/press
- Media
  - podcasts/[podcast]
  - conferences/[event]
  - graphics

Suggestions?

**Comment by TheEnthusiasticAs** [comment]
Perhaps, we should not have "press" there. It includes: Price analysis, news by journalists (X is partnering with Y. Only original sources). 

Other lgtm and I have nothing to add at the moment.

**Comment by hitchcott** [comment]
Speaking of which, while I am doing this restructuring, we can add tags for different articles and links. Any suggestions on what those tags/categories should be?

- Development
- Mining
- Education
- Trading
- Guides
- Wallets
- Exchanges
- Events
- Teams

**Comment by TheEnthusiasticAs** [comment]
My suggestions with comments:

Development
Mining
Education
~~Trading~~ (pls no price topics, otherwise it will get spammy)
Guides
~~Wallets~~ (What do you mean here? New listings? I would not do any announcements on the website, otherwise it will get spammy)
~~Exchanges~~ (What do you mean here? New listings? I would not do any announcements on the website, otherwise it will get spammy)
Events
Teams (only a short message with undermined link to the official page, like this one) 
![image](https://user-images.githubusercontent.com/48069525/79077869-a9c7b480-7d04-11ea-963f-4d755f17b7a9.png)

**Comment by hitchcott** [comment]
> Perhaps, we should not have "press" there. It includes: Price analysis, news by journalists (X is partnering with Y. Only original sources).
> 
> Other lgtm and I have nothing to add at the moment.

The blog and press sections are separated to indicate that one is for articles that exist on this website, and the other is for external links.

**Comment by hitchcott** [comment]
@TheEnthusiasticAs there are quite a few trading/exchange related items that exist right now in the list, like:

![image](https://user-images.githubusercontent.com/1696942/79385387-68334580-7f60-11ea-9de6-13e1cb972d91.png)

Will these be deleted? I will add support for those tags now but you can delete them if needed

**Comment by TheEnthusiasticAs** [comment]
Because those are the part of the ETC history, listings, they will not deleted. But those with price analyzes should be deleted, I would suggest. cc @gitr0n1n

**Comment by gitr0n1n** [comment]
Agreed. I think its important to leave articles like "x exchange lists ETC" or "x wallet add ETC" so there is a documented history of that in the back fill. Moving foward if a new exchange or product supports ETC it will likely be listed so people are aware. So just trying to make the past reflect the likely future for anyone going "Is ETC dead? I haven't seen the website updated in two years"

I think ANY article related to price/market cap should be removed though.

To clarify simply:
Pro "Ecosystem" articles.
Anti "Speculation" articles.

**Comment by hitchcott** [comment]
Given that we have the tags, do we actually need to do anything more here?

@gitr0n1n @TheEnthusiasticAs

**Comment by gitr0n1n** [comment]
No i think its great as is. I'm okay with thi issue being closed.

**Comment by TheEnthusiasticAs** [comment]
me as well. cc @stevanlohja

**Comment by hitchcott** [comment]
Cool, let me know if this should be re-opened.
