### ISSUE TITLE
Investigate Build Times

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#460]
Each build is taking around 5 minutes on netlify which seems excessive, especially as caching is supposed to be enabled.

See if there's anything that can be done to reduce the build time.

**Comment by gitr0n1n** [comment]
I'm guessing its the Blog images. Can those be compressed and optimized?

**Comment by gitr0n1n** [comment]
Also, opposed uploading the same file into multiple folders like a hardfork image or the ECIPs image, would it be better to have it in one blogs/image folder?

**Comment by hitchcott** [comment]
@gitr0n1n can you point out where the duplicates are?

I think that yes we can do a shared folder

**Comment by gitr0n1n** [comment]
Yeah i set them up with ECIP image on top and then hardfork image below:

Example: https://github.com/ethereumclassic/ethereumclassic.github.io/tree/master/content/blog/2019-05-30-core-devs-call-atlantis-call

and

https://github.com/ethereumclassic/ethereumclassic.github.io/tree/master/content/blog/2019-06-07-core-devs-call-atlantis-scheduling

**Comment by gitr0n1n** [comment]
also these are just pulled from the media kit. So could be high res. So if you have an optimization tool to auto reduce their file size and resize to an appropriate width for the page, that would be awesome.

I tihnk i saw a PR in the past where someone rolled through and did that.

**Comment by gitr0n1n** [comment]
Here was the Lossless image optimization PR:

https://github.com/ethereumclassic/ethereumclassic.github.io/pull/356

**Comment by hitchcott** [comment]
That image optimisation has already been applied. Also the images are automatically resized and optimised during the build process for production.

I'm investigating this, I'm pretty sure it's to do with caching plugins.

**Comment by hitchcott** [comment]
Problem solved. I have switched to using a different caching plugin, a typical build should now deploy in around 2 minutes (once I merge this next update)...

![image](https://user-images.githubusercontent.com/1696942/80727712-f3ced980-8afd-11ea-9f71-b91918d9337a.png)
