### ISSUE TITLE
Incorrect dated blog article?

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#467]
@gitr0n1n 

Is this meant to be in 2020?

https://github.com/ethereumclassic/ethereumclassic.github.io/tree/master/content/blog/2020-03-17-5m20-era3-block-reward-reduction

**Comment by gitr0n1n** [comment]
yes, era 3 happened last month

**Comment by hitchcott** [comment]
Okay, I was confused because the content seems to be repeated from an older post, but if it's intentional that's no problem. 

Feel free to close this issue if it's intended.

**Comment by gitr0n1n** [comment]
it's intentional, It's the ECIP-1017. Thanks!
