### ISSUE TITLE
Should we have a Merchant page?

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#471]
I was just reviewing https://cryptwerk.com/pay-with/etc/ and noticed there are a ton of merchants. Should we have a page designated for these companies?

**Comment by TheEnthusiasticAs** [comment]
It is more efficient (with the time the list will become too long - millions) to let e. g. cryptwerk manage those and etc website will list in turn those managers.

**Comment by gitr0n1n** [comment]
Good point! I'll close this comment.
