### ISSUE TITLE
Two different Stat pages with the same stat link at the end

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#478]
ETCStats and 2Miners Network statistic links are leading to the 2Miners statistic dashboard:

1. http://etcstats.org/
2. https://2miners.com/etc-stats/

The 1st one can be deleted!?
![image](https://user-images.githubusercontent.com/48069525/82158117-16931900-9886-11ea-91ad-8cab388f5991.png)

**Comment by gitr0n1n** [comment]
Good catch. Some of these are domains I bought to donate to the project, but they aren't live yet. So I'm removing them in this PR and will only add back once officially setup.

https://github.com/ethereumclassic/ethereumclassic.github.io/pull/479

issue is addressed. Going to close this one. Nice catch @TheEnthusiasticAs
