### ISSUE TITLE
Update network resources

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#482]
delete:
https://etcstatus.live/ (no longer maintained atm)

add:
Only Phoenix related: https://phoenix.fault.dev/ (an alternative to the above)
Only Phoenix related: https://ph03n1x.fault.dev/ (an alternative to the previous one: it has a different set of nodes connected)

**Comment by gitr0n1n** [comment]
please setup the PR for review @TheEnthusiasticAs

**Comment by TheEnthusiasticAs** [comment]
yes, will do. I put it as a note.

**Comment by TheEnthusiasticAs** [comment]
See closed PR #483
