### ISSUE TITLE
Apply for Netlify Open Source

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#488]
Seems this project should quality.

Main benefit is that the hosting team can have infinite members.

https://www.netlify.com/legal/open-source-policy/

**Comment by gitr0n1n** [comment]
> Seems this project should quality.
> 
> Main benefit is that the hosting team can have infinite members.
> 
> https://www.netlify.com/legal/open-source-policy/

@hitchcott have you filled out this form yet?

**Comment by hitchcott** [comment]
No not yet, I will do this shortly. But first we need to:
 
- Include a code of conduct
- Add a "This site is powered by Netlify" link on the footer

I'll do this during the next round of updates.

**Comment by hitchcott** [comment]
This is now accepted and we are using the Teams hosting. 

LMK if anyone wants an invite.
