### ISSUE TITLE
Request to be added to your list of Ethereum Classic supporting exchanges

### ISSUE THREAD

**Issue by rzel** [ethereumclassic/ethereumclassic.github.io#498]
We are an exchange that is fully invested in supporting Ethereum Classic currency. We would really appreciate if you could add us to your list of exchanges that support Ethereum Classic. You can find us at https://bitni.com.

Is this possible?

Thanks
Rob

https://bitni.com
contact@bitni.com

**Comment by TheEnthusiasticAs** [comment]
hey @rzel. Welcome! I opened a PR #499 for adding your exchange.

**Comment by rzel** [comment]
Thank You!

**Comment by gitr0n1n** [comment]
Successfully Merged PR https://github.com/ethereumclassic/ethereumclassic.github.io/pull/499

This issue was addressed and can be closed. See live changes here:
https://ethereumclassic.org/ecosystem/exchanges

Thanks for reaching out @rzel . Glad to learn of long term support for ETC.
