### ISSUE TITLE
Add Video

### ISSUE THREAD

**Issue by dax-classix** [ethereumclassic/ethereumclassic.github.io#50]
@ProphetDaniel has asked me to add https://www.youtube.com/watch?v=KzVhP4SOS5U

Approve?

**Comment by NDNewell** [comment]
Great effort, but the voiceover is difficult to understand.


[image: photo] Nicholas Newell
Front-end Developer
+44 07490 200 466 || rebelexplorer31@gmail.com ||
https://github.com/NDNewell
<http://www.facebook.com/nicholas.rmit>
<http://uk.linkedin.com/in/nicholasdnewellwebdeveloper>
<http://twitter.com/NicholasDNewell>
Latest Tweet: <https://twitter.com/NicholasDNewell> The future will be
decentralized https://t.co/NseThtcYJ1 #blockchain
<https://twitter.com/blockchain> #Bitcoin <https://twitter.com/Bitcoin> Read
More <https://twitter.com/NicholasDNewell/statuses/768190492127457280>
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=603015497755646>

**Comment by ProphetDaniel** [comment]
@NDNewell, I agree with you. Maybe a native speaking person is better suited for making the voice of it. We need a volunteer for this task.

**Comment by arvicco** [comment]
Yes, native English speaker voiceover would be nice. Here is a video version without voice channel: https://www.youtube.com/watch?v=hg3nH5pmqhI

**Comment by realcodywburns** [comment]
Has any progress been made on this?

**Comment by arvicco** [comment]
Nope, no one volunteered a native-English voiceover so far.

**Comment by ProphetDaniel** [comment]
The task at hand is to transform this https://www.youtube.com/watch?v=hg3nH5pmqhI to https://www.youtube.com/watch?v=-Dx6fVQnMw4 but with a native speaker.

**Comment by ProphetDaniel** [comment]
Twitter call for action: https://twitter.com/dani_kase/status/868614710899376128

**Comment by jeremyburr** [comment]
I'm happy to volunteer. Is there an English transcript I can use?

**Comment by ProphetDaniel** [comment]
That is great @jeremyburr. Talk with Andriy Savdeyev in slack (@savandra in Github). He is the guy who made the video and he might have the transcript. Or else you will have to transcript yourself the original video's audio.

**Comment by jeremyburr** [comment]
@savandra, I've sent out a Slack message for you. I'm volunteering to do the English voice over but I cannot find a transcript or video dialogue to use. I only speak English.

**Comment by realcodywburns** [comment]
Closing unresolved. Video is no longer availiable
