### ISSUE TITLE
Add depcreated clients

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#532]
Make it clear these are older clients that are only supported up to X relase.

Discussed here: #531

**Comment by gitr0n1n** [comment]
I think after this week we probably want to move away from all deprecated clients and keep the clients page to RECOMMENDED only clients so the hashrate is landing on secure LTS software. Do you tihnk we can close this one @TheEnthusiasticAs and @hitchcott ?

**Comment by TheEnthusiasticAs** [comment]
Yes, @gitr0n1n it can be closed and I agree with you fully.

**Comment by gitr0n1n** [comment]
Sounds good. Closed.
