### ISSUE TITLE
Change warning to recommend switching to a new client

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#534]
Explain OpenEtheruem situation?? @TheEnthusiasticAs @gitr0n1n

**Comment by gitr0n1n** [comment]
OE only have ETc support in v 3.0.1

Any other version in not compatible with the ETC network.

So 3.0.2 will not be compatible as they have dropped ETC support. Miners wishing for a node that support both ETC and ETH should consider moving to Core-Geth, Besu, or OpenETC

**Comment by TheEnthusiasticAs** [comment]
The last supported version of the Multi-Geth for Agharta is v1.9.14. There is also an addition "... or higher...." on etcnodes' site. I am not a technical guy, so can't not say, whether the higher versions support ETC. The informations can be found here: https://github.com/multi-geth/multi-geth/releases.

![image](https://user-images.githubusercontent.com/48069525/88678522-d60a1400-d0ee-11ea-8806-9d3e7c8a906f.png)

**Comment by gitr0n1n** [comment]
Yeah so Multi-geth will have a range starting with 1.9.14 and ending with the release that officially deprecates ETC support.

OE will only have their 3.0.1 release that is compatible with Phoenix.

All LTS clients for ETC also support ETH so they should be suggested as an alerntive to the ETH only clients. Especially as OE has annouced intent to limit support to only the ETH EVM in the long term.

**Comment by hitchcott** [comment]
Covered in #544
