### ISSUE TITLE
The search engine is not searching on the News page

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#538]
Tested search keywords
![image](https://user-images.githubusercontent.com/48069525/89075956-a160bb80-d37f-11ea-9ede-25e385e21d36.png)
![image](https://user-images.githubusercontent.com/48069525/89076007-bb020300-d37f-11ea-8ab7-bd63c8068c0b.png)

**Comment by hitchcott** [comment]
Thanks for this @TheEnthusiasticAs , the behaviour right now is to only check pages *within* the website (not extenral links).

I can change this to add links to external links from news section.

**Comment by TheEnthusiasticAs** [comment]
This page counts to external links?
![image](https://user-images.githubusercontent.com/48069525/89101821-e62e3600-d403-11ea-8223-f173849e80c8.png)

If, so, yes, then please do it. It is helpful there as well. Thank you!

**Comment by IstoraMandiri** [comment]
Fixed in #654
