### ISSUE TITLE
Front Page Refresh

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/ethereumclassic.github.io#545]
To make it seem more alive!

> a.s.: i kinda wonder why ethereumclassic.org looks so abandoned. given that it's about the first thing you find when looking for ETC, shouldn't it at least feature some links to useful information on the first page ? e.g., a status page about that chain split incident and its aftermath. instead, it show a hard fork alert for phoenix. handy if you just got back from an interstellar mission on which your your comms gear had failed, but ...
> 
> oh, good. but i wonder if this shouldn't be a bit more visible. when i go to ethereumclassic.org, i see 1) a marketing message, 2) info about last year's summit, and 3) a phoenix hard fork alert. all that basically suggests that this is the wrong place for more than very superficial and not too urgent information.
> if i scroll down, i get a very high-level introduction. then get started. and finally, at the very end, the news. i would think that especially something like the on-going chain split situation should feature more prominently. maybe not a pop-up like the - now rather dated - phoenix alert, but maybe a box or so. we can tell by looking on discord, where very similar questions keep repeating, that there's a bit of a gap between what people want to know and what they're able to find on their own :)
> 
> 
> Suggestion based on your comment:
> The reorg info can be put in the red banner, too. The order:
> 1) reorg info with the link to the news page 
> 2) last hardfork
> 
>

**Comment by gitr0n1n** [comment]
Yes the ETC Summit was 10 months ago. I think those are great comments and feedback on the needs of the frontpage. I'm excited to see what you come up with @hitchcott

**Comment by TheEnthusiasticAs** [comment]
an comment from @wpwrak to the updated front page from discord:
_hmm, what exactly changed ? the first page now looks a lot more relevant than it did a while ago, so that's good. the left-hand side could benefit from a clearer indication that there's more below. maybe "More", down arrows, or both ? a problem with this kind of vast empty space design is that one can easily overlook that there's also a scrollbar. (i guess the triple-bar menu leads to the same kind of information, too, just with a layer in the middle)_

**Comment by hitchcott** [comment]
Thanks @TheEnthusiasticAs but I'm having trouble interpreting that comment - perhaps some more visual feedback would help clear things up?

**Comment by TheEnthusiasticAs** [comment]
Yes, here in my example all three elementes - 2 arrows on the page flanks and a "More" text should scroll the page down with a click:
![image](https://user-images.githubusercontent.com/48069525/102010726-40d78700-3d40-11eb-97b2-3994a5243568.png)

The opposite is the same. When you are on the bottom of the page, the arrows should direct to the top

**Comment by wpwrak** [comment]
Yes, that's the place I meant. Right now, it can be easily be mistaken for being purely decorative.
Also, looking further down, shouldn't the line continue above "Participants" ?
