### ISSUE TITLE
Fade out OpenETC?

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#549]
On the teams page, OpenETC is listed as active, is it?

**Comment by ondertitels** [comment]
OpenETC is not active anymore. You might want to change the font in the search bar to the same font on the website + uppercase 👍

**Comment by TheEnthusiasticAs** [comment]
opening a PR for the deleting

**Comment by gitr0n1n** [comment]
Merged. https://github.com/ethereumclassic/ethereumclassic.github.io/pull/550
