### ISSUE TITLE
Draft: Create a Treasury FAQ for Easy Understanding

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#556]
As we learn the deep mechanics of the Treasury proposal. Can we aggregate an FAQ that will be easy for the less informed to learn about this development? Let's aggregate the details here and we can draft up a subsection to add to https://ethereumclassic.org/knowledge/faqs

**Comment by TheEnthusiasticAs** [comment]
If it get a rough consensus, yes, the FAQ can be put there

**Comment by hitchcott** [comment]
Can we close this?
