### ISSUE TITLE
Duplicate Blog Entry

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#560]
https://ethereumclassic.org/blog

Seems there are two URLS

https://ethereumclassic.org/blog/2020-08-28-core-devs-call-2020-Q3-Hardfork-Evaluation-Consensus-Finding
https://ethereumclassic.org/blog/2020-08-20-core-devs-call-2020-Q3-Hardfork-Proposal-Gathering

Please let me know which one needs deleting.

**Comment by TheEnthusiasticAs** [comment]
cc @gitr0n1n

**Comment by TheEnthusiasticAs** [comment]
they are both different @hitchcott
https://github.com/ethereumclassic/ECIPs/issues/333

**Comment by hitchcott** [comment]
Okay, my bad sorry
