### ISSUE TITLE
Add ECIP-1092 to Core ECIP Draft list

### ISSUE THREAD

**Issue by padenmoss** [ethereumclassic/ethereumclassic.github.io#566]
Please add https://github.com/ethereumclassic/ECIPs/issues/327 as ECIP-1092 to Core ECIP Draft list

Number; 1092
Title: Mining Penalty for Deep Reorganization
Author: @Dexaran

(See issue 327 for ECIP body)

**Comment by developerkevin** [comment]
ECIPs are proposed under Pull Requests of the ECIP Repo and Dex's proposal has been given the "Core" label. https://github.com/ethereumclassic/ECIPs/pull/328

**Comment by padenmoss** [comment]
The "Core" label already being designated, yet I do not see ECIP-1092 listed at https://ecips.ethereumclassic.org/core

**Comment by developerkevin** [comment]
Yes there are still a few that need to be added onto the ecips site.

**Comment by q9f** [comment]
It's fixed.
