### ISSUE TITLE
most of the instant exchanges named on the wiki don't take etc anymore

### ISSUE THREAD

**Issue by TheAquabat** [ethereumclassic/ethereumclassic.github.io#578]
most of the exchanges on this page

https://ethereumclassic.org/ecosystem/exchanges

don't take ETC anymore. Is this going to be fixed? I mean are 51% attacks going to stop? the wiki needs fixing.

**Comment by TheAquabat** [comment]
of the ones I check the only instant that's working is ChangeNOW.

**Comment by TheEnthusiasticAs** [comment]
closing this channel as it is not repo-related.
