### ISSUE TITLE
Add CEX

### ISSUE THREAD

**Issue by UlasLiteBit** [ethereumclassic/ethereumclassic.github.io#584]
Hi,

We have been trading ETC for a long time. Can our exchange be added to the CEX list?

Exchange name: LiteBit
Link: https://www.litebit.eu/en/buy/ethereumclassic

If any more information is needed, let me know. Thanks in advance!

**Comment by TheEnthusiasticAs** [comment]
Hi @UlasLiteBit! No further infos are needed ;-). I pushed a PR for it. It will go through the approval process. At least two approvals are required.

**Comment by TheEnthusiasticAs** [comment]
it is added now. I am closing this issue
