### ISSUE TITLE
Add Profiles page

### ISSUE THREAD

**Issue by igetgames** [ethereumclassic/ethereumclassic.github.io#59]
I would like to add a page that lists all active ETC developers and contributors, with a short bio, and a list of projects they have initiated, maintain, or contribute to, both open source and commercial (there are currently three companies that I am aware of bootstrapping on ETC).

I will begin this task when I return from CppCon this Wednesday, the 21st.

@elaineo @ProphetDaniel @splix @dax-classix @arvicco @whatisgravity @realcodywburns @sethfork @avtarsehra @chucksrq @CarloVetc

**Comment by arvicco** [comment]
Now a separate ETCDEV team site: https://www.etcdevteam.com/
