### ISSUE TITLE
Development/contribute page + the blog pages: The red pop-up box and the ETC discord links weren't auto-updated

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#591]
Hi @hitchcott!

https://ethereumclassic.org/development/contribute:

1. Red pop-up box: Contains the old infos and wasn't auto-updated as on the other pages (tested on several browsers and empted the cache, too)
![image](https://user-images.githubusercontent.com/48069525/96332295-55124700-1063-11eb-89e8-4683b897194d.png)

2. The ETC discord link on the end of the main page content, the blue one at the end of the page and the another one under the "social" weren't auto-updated as on the other pages

I suspect these have to do with the website codes. Might you look into these, pls? Thank you!

**Comment by gitr0n1n** [comment]
interesting, I see the update in the preview of your most recent PR @TheEnthusiasticAs . Hopefully it self corrects when that PR is approved.

**Comment by TheEnthusiasticAs** [comment]
I still have the issues @gitr0n1n. I opened the directory in Edge browser.
![image](https://user-images.githubusercontent.com/48069525/96361252-68d1b200-1124-11eb-810a-c66d586f539d.png)

**Comment by gitr0n1n** [comment]
On the preview I see it's undated via Brave browser. I recommend clearing your cache.
![Untitled](https://user-images.githubusercontent.com/58588775/96492401-d226f300-1200-11eb-8b85-fa627a37c785.png)

**Comment by gitr0n1n** [comment]
This appears live on the main site for me. @TheEnthusiasticAs So you can likely close this issue.

![Untitled](https://user-images.githubusercontent.com/58588775/96493875-c9cfb780-1202-11eb-82f2-ab1df9cd708e.png)

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n now pls go to this page: https://ethereumclassic.org/development/contribute. There is another content in the red box. Dito for the etc discord links there

**Comment by gitr0n1n** [comment]
Oh i see! yes I see the different box on that sepcific link.

**Comment by TheEnthusiasticAs** [comment]
I noticed the same on blog pages. One is even from August: 
_https://ethereumclassic.org/blog/2020-09-11-core-devs-call-ecip-1043-1049-1099-qa_
![image](https://user-images.githubusercontent.com/48069525/97777358-f6bf8b00-1b6f-11eb-8707-5e66e32c61d7.png)
https://ethereumclassic.org/blog/2020-10-02-core-devs-call-15-ecip-1049-keccak-breakout-session
![image](https://user-images.githubusercontent.com/48069525/97777367-02ab4d00-1b70-11eb-8216-b9a8d9d099c2.png)

**Comment by hitchcott** [comment]
Triggered a cache-busting rebuild and it seems to have fixed this. 

Please confirm / close this issue if it has.

**Comment by TheEnthusiasticAs** [comment]
Confirming, the issue was solved. Here an evidence. One from the contribute page: 
![image](https://user-images.githubusercontent.com/48069525/97902493-fecd2580-1d3d-11eb-822e-16daa6abc7ed.png)

Thx hitchcott
