### ISSUE TITLE
DAG Monitor

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#608]
@hitchcott thoughts on a DAG countdown clock for when ETH cards will need to migrte to ETC and then when card will be obsoleted on ETC

Example: after Thanos a Countdown for 4GB and 6GB becoming obsolete on ETH DAG. And a countdown for 3GB becoming obslete on ETC

**Comment by gitr0n1n** [comment]
Here is a nice metric display for ETC @IstoraMandiri.

Can we get something up like this for quick and trusted metrics?
https://grafana.mariomichel.com/d/5S-6O8VZk/hyperledger-besu-node-at-ethereum-classic?orgId=1&refresh=5s

**Comment by IstoraMandiri** [comment]
@gitr0n1n 

This, as well as your other requests for dashboards, is not something that's possible within the scope of this website project, as it requires a backend data layer, it is not just a statically generated frontend.

Please could you close those 4 issues and assign to a different project or team?
