### ISSUE TITLE
Add Filtering Option to the Guides and Tools pages

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#610]
I was looking at the Guides section. It's getting pretty long and cluttered. Do you think you could setup something like the news articles, where we have a filter by topics? Exmaple: "Mining" "Development" "Tools" "Configuartions"? @hitchcott

**Comment by IstoraMandiri** [comment]
@gitr0n1n now that we have the new category and also a much improved search function, can we consider this solved?
