### ISSUE TITLE
how to enable testnet

### ISSUE THREAD

**Issue by tncsource** [ethereumclassic/ethereumclassic.github.io#619]
hi everyone please let me know how to enable testnet ETC and i want to get faucet testnet coins for ETC so please give me any site or any way to i can get coins thank you

**Comment by TheEnthusiasticAs** [comment]
hi. You are asking in the inappropriate repo. It is here for the website developments. Please ask here: https://github.com/ethereumclassic/ECIPs/. I am closing it here.
