### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by Jaska8** [ethereumclassic/ethereumclassic.github.io#639]
Main site has been inaccessible for few days now due Invalid SSL cert.

**Comment by gitr0n1n** [comment]
@hitchcott Let me know if we need to migrate the website to the community's EthereumClassic.com if DFG is not maintaining EthereumClassic.org . Feel free to ping.

**Comment by realcodywburns** [comment]
you need to update the cname on the .com to point to the netlify site.

**Comment by gitr0n1n** [comment]
@TheEnthusiasticAs @bobsummerwill @hitchcott @realcodywburns 

It' my understanding there is an emotional meltdown happening with the usual suspects in Discord. @developerkevin banned my discord account a few months back when we didn't agree on ECIP-1047. Feel free to ping me on github if you guys would like to migrate the ethereumclassic.github.io to the EthereumClassic.com domain. @hitchcott and I spoke about this eventually happening back when DFG acquired the .org. So this was expected at some point.

@hitchcott If I remember from our conversations, I believe we need to update the code to build with the .com TLD for netifly to build the website properly to the community owned EthereumClassic.com.

Again, ping me on github and I can dedicate some time to working with you to make that migration a success. In the meantime, the blocker is on @hitchcott or someone else familiar with the netifly build.

In the meantime, I am busy working on other projects. Namely my cryptocurrency exchange: https://trade.mandala.exchange (which supports Ethereum Classic).

**Comment by bobsummerwill** [comment]
Hey @gitr0n1n,

I have been trying to troubleshoot today and spoke to Terry this afternoon.
They have a new SSL certificate.
We just need to work out the "plumbing", which looks like it includes CloudFlare, as well as the DNS and Netlify settings.
There is no malicious anything here, just the SSL screw up and then spaghetti to tie back together.

@hitchcott If you see this, please could you drop me an email at bob@etccooperative.org and I can loop you in on a thread with Terry and co to try to get this resolved?   Thanks!

We can certainly look at mapping to other URLs, but need to actually work out how the current setup works first so we can fix it.

**Comment by hitchcott** [comment]
@bobsummerwill email sent

**Comment by hitchcott** [comment]
With regards to migrating domains, if this is something we have consensus on then I'm happy to help.

It will be no small feat though, and we would ideally need to maintain the old `.org` address for redirects indefinitely.

I would really only support migrating to `.com` if it's critical.

**Comment by developerkevin** [comment]
> @TheEnthusiasticAs @bobsummerwill @hitchcott @realcodywburns
> 
> It's my understanding there is an emotional meltdown happening with the usual suspects in Discord. @developerkevin banned my discord account a few months back when we didn't agree on ECIP-1047. Feel free to ping me on github if you guys would like to migrate the ethereumclassic.github.io to the EthereumClassic.com domain. @hitchcott and I spoke about this eventually happening back when DFG acquired the .org. So this was expected at some point.
>

@gitr0n1n , I think we should keep the discussion in here about what's happening in here. However I feel I should address your allegation—I  never did any such thing. People often disagree strongly with each other, but I don't believe that makes it right for one party with privileges to think about removing someone forever. In all honesty, I try only banning scammers spamming links, use the timeout function mostly, or kick out those who’re openly breaking rules and allow them to return if so they choose. Looking at the "server settings" and "audit"  you're account is not in the banned section, unless you deleted that account and are one of many who've done so.

Anyway you've been free to return at any time. I'm also not the only mod/admin in the DIscord. Banning someone imo, is the wrong choice. Kicking and having them return as say "account v2" is more fair. If you're open to it, how about we bury this "hatchet" we have right now? feel free to join again. 


As for domains I hold the ethereumclassic.global - doesn't roll off the tongue but its something. I've also got ethclassic.co but need to straighten some things out with that one.  Also I  agree with Hitchcott re: staying away from com, or .co likely until its 100% needed.

**Comment by gitr0n1n** [comment]
> With regards to migrating domains, if this is something we have consensus on then I'm happy to help.
> 
> It will be no small feat though, and we would ideally need to maintain the old `.org` address for redirects indefinitely.
> 
> I would really only support migrating to `.com` if it's critical.

To be clear @hitchcott it was the community in discord #general that were petitioning for the migration from the .org to the .com. I was pinged about it in DM. I don't really care what you guys decide, I was just letting you know I'm available to help out if you guys need me. I was given these domains as a good steward by Cody. I didn't request them. I'm happy to set aside some time to work on this migration if its needed. In the meantime, I'll be working on my own project: https://trade.mandala.exchange

**Comment by gitr0n1n** [comment]
This appears to be resolved.

**Comment by TheEnthusiasticAs** [comment]
yes, it can be closed @gitr0n1n
