### ISSUE TITLE
Link broken on the main website

### ISSUE THREAD

**Issue by jatin-pahuja** [ethereumclassic/ethereumclassic.github.io#649]
[The IOHK link on the participants section of the homepage is broken and shows a 404 error](https://iohk.io/projects/ethereum-classic/)

**Comment by drospa** [comment]
IOHK website changed. There isn't a section for the Mantis team now. We can reference this https://iohk.io/en/technology/ or directly https://mantisclient.io/

**Comment by TheEnthusiasticAs** [comment]
I opened the PR #650 to update several IOHK references on the website. Thx for the heading up to it
