### ISSUE TITLE
Add Trustee Wallet to SOFTWARE WALLETS

### ISSUE THREAD

**Issue by taki-183** [ethereumclassic/ethereumclassic.github.io#653]
Hi!
It is a Trustee Wallet team. 
We have added a Etherem Classic to our wallet, so please place a link to our application in the SOFTWARE WALLETS section of your website.

Name: Trustee Wallet
Site: https://trusteeglobal.com
GitHub: https://github.com/trustee-wallet

**Comment by TheEnthusiasticAs** [comment]
I opened the PR #655

**Comment by taki-183** [comment]
> I opened the PR #655

Thanks
