### ISSUE TITLE
Better search function

### ISSUE THREAD

**Issue by w1g0** [ethereumclassic/ethereumclassic.github.io#654]
-Firstly, can the search function be integrated at the top of the pages in stead of linked with the hamburger menu, even with a dropdown mouseover if one deems that 'cleaner'.

-Secondly, can the search function go wider? For example the 'block explorers' can't be found.

-Third, it would be great to be able to link to the mid of a page using the # 
e.g. https://ethereumclassic.org/development/network-resources#blockchainexplorers

ps: Can the name be changed to block explorer? It feels more intuitive for searching between blocks on the blockchain rather than looking for a blockchain in the space.

**Comment by hitchcott** [comment]
Thanks @w1g0 , these are good suggestions.

As for 3 - this is already the case -- https://ethereumclassic.org/development/network-resources#blockchain-explorers

You can inspect element and check next to the header for the ID, but it should be lowercase with dashes

**Comment by IstoraMandiri** [comment]
New version has AI powered agolia search, scraping content, with multiple categories

![image](https://user-images.githubusercontent.com/1696942/145416487-bb34fe45-ae31-4b32-8345-7d30653573cc.png)
