### ISSUE TITLE
Remove Apps and Protocols Section

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/ethereumclassic.github.io#675]
As ETC prepares for it's next stage of explosive growth, I think it's a good idea for us to remove the Apps and Protocols http://ethereumclassic.org/ecosystem/apps-and-protocols section, as it will be increasingly likely that scams and otherwise grey area projects get listed, and moderation would be potentially biased or conflicting.

It is also always out of date and difficult to tell when projects need removing. I suggest we link to some external dapps list.

Thoughts?

**Comment by w1g0** [comment]
An external list would be a good solution, another idea would be to create an automatic mailing list to ask if projects are active once listed.

**Comment by gitr0n1n** [comment]
No Objections from me. I agree about the risk you hightlight.

**Comment by TheEnthusiasticAs** [comment]
Yes, the risk is there. Let's disable that section. But to link to some external dapps list is just shifting the issue. The problem will still be there.

**Comment by w1g0** [comment]
It's good for now but we need a solution for the midterm, without links in the future is a safe option but it seems odd to me.

**Comment by w1g0** [comment]
If you allow me to freestyle here, I was thinking of a review system that let's community members (at least with Discord 'supporter' role for example) test before listing and comment once listed on the dApp webpage without any responsibility and the necessary disclaimers.

**Comment by w1g0** [comment]
> For this they also should do test video(s) of the corresponding project, so the interested can see, that the tester is not faking. Also, they should be honest, when they do the video. If something is not good or bugged, they should show it up.
>
That sounds like a good idea.

> The solution is not obvious and different topic imo but wrt a review system, i would also urge the discord mods not to give "supporter roles" to quickly. As soon as a metric is made it often becomes abused. Maybe other reputable systems and account holders like Github, gitter could also be able to review and they also get differentiated. Another shower thought is that only an ETC account can make a review. You need to spend an ETC tx to make that review + the reviewers reputation stays with that unique ETC account. Discord supporters roles could publicly link themselves to their ETC address for reviewing and reputation.
>
The Discord supporter role was merely a random example of verification. A forum member with a certain amount of helpful posts would be another.

When you speak of spending ETC to review it sounds like a dApp and I'm not sure it is helpful to link a wallet address to a identity even if it were pseudonymous.

**Comment by IstoraMandiri** [comment]
To udpate this, I've removed apps from the front page once #693  gets merged.

But I'm still not sure about removing all the apps completely and linking to a remote site. I kind of like having at least somewhere to keep a reference of them, I just don't think they should be on the front page necessarily, and plenty of warnings needed.

But then there would be zero, or very minimal, moderation. Perhaps have an additional badge for 'vetted' stuff?

https://ethereum.org/en/dapps/#explore

**Comment by IstoraMandiri** [comment]
New version implements apps in a way that makes it clear they are not vetted, with a big warning message.

They are also separated from the main news section so new apps don't clutter up important announcements
