### ISSUE TITLE
ETC PRICE SOURCES

### ISSUE THREAD

**Issue by gozames** [ethereumclassic/ethereumclassic.github.io#717]
Hello,

https://ethereumclassic.org/ecosystem/exchanges at this page almost all stat sites.

Whats about to include coin lore also

Thanks

**Comment by gitr0n1n** [comment]
Hi @gozames if you'd like to add an exchange to that list, please open an PR and drop that exchange in the list. It is organized by Alphabetical letter. When the PR is submitted, we'll give it a review and it the link checks out, the exchange will be added to the list. Please use the link that directs to the ETC/USDT market! Thanks Much!

**Comment by IstoraMandiri** [comment]
@gitr0n1n please can we keep these open as long as it remains unresolved, so we can keep tabs on it

**Comment by gitr0n1n** [comment]
> @gitr0n1n please can we keep these open as long as it remains unresolved, so we can keep tabs on it, thank you

Yeah, that seems like a good approach.

**Comment by maxpatalec** [comment]
Hi, 

https://github.com/ethereumclassic/ethereumclassic.github.io/pull/718

**Comment by gitr0n1n** [comment]
Going to close now that a PR is submitted. Thanks!
re: https://github.com/ethereumclassic/ethereumclassic.github.io/pull/718
