### ISSUE TITLE
create an app

### ISSUE THREAD

**Issue by ClassicMedusa** [ethereumclassic/ethereumclassic.github.io#763]
Hey, we're a brand new nft project on ETC we would like to be on the ETC website to grow easily and provide our services as quickly as possible

could u add us on the app section as NFT?

-our twitter: medusa_classic
-our discord; https://discord.gg/AHaNhu4RDQ

**Comment by IstoraMandiri** [comment]
Do you have a website?

**Comment by w1g0** [comment]
@ClassicMedusa ?
