### ISSUE TITLE
Mining Pool Updates

### ISSUE THREAD

**Issue by Jamyye** [ethereumclassic/ethereumclassic.github.io#767]
Hi there, 
Request is to update the list of mining pools. Some are broken links and I would like to add 2 others. 

I checked these links myself, and ones that wouldn't open I then checked with isup.me to see if it was Geo filtered. I am based in USA

Broken to be removed: 
https://etc.1stpool.org/
https://www2.coinmine.pl/etc/
https://www.coinotron.com/ (website active but notice that they are shutdown is displaying)
https://crypit.net/?pool=ETC 
https://etc365.org/
https://ethereumclassicpool.com/
http://etcturk.sytes.net/
https://ethashpool.com/
https://etc.fairpool.xyz/
https://firepool.com/
https://hash.express/ (no etc pool found on website)
http://ww62.kdv-mining.com/#/ 
https://etcpool.phoenixmax.org/ (redirects to spam website)
http://etc-solo.pool-node.com/
https://etc.saturnpool.com/
https://startmining.pl/ (redirects to wordpress website for seo)
https://uupool.cn/etc/

Pools to be added:
http://etcpool.us
https://etc.baypool.org/

Warm regards,
Jamyye

**Comment by Jamyye** [comment]
Page is here: https://ethereumclassic.org/mining/pools

**Comment by Jamyye** [comment]
Update, pool.btc.com has added etc pool back - it should stay

**Comment by gitr0n1n** [comment]
PR Submitted. Thanks for the open source contribution to Ethereum Classic.
