### ISSUE TITLE
Dead links on Wallets page of ethereumclassic.org website

### ISSUE THREAD

**Issue by TheMisplacedPhilosopher** [ethereumclassic/ethereumclassic.github.io#782]
1. The link to Emerald wallet on the page https://ethereumclassic.org/services/wallets is no longer valid. The Emerald wallet is now located at https://emerald.cash/
2.  The Citowise website does not open. Have tried multiple times. No post on their Twitter page either. Maybe they are not providing wallet service anymore. Please investigate and remove the link. 
3. HubrisOne wallet link does not work. Their wallet page is now at https://hubrisone.com/wallet Please update.

**Comment by TheMisplacedPhilosopher** [comment]
These links are not working:
Saturn Wallet - https://www.saturn.network/blog/saturn-wallet-user-manual/
I tried Chrome webstore but that too does not work - 
https://chrome.google.com/webstore/detail/saturn-wallet/nkddgncdjgjfcddamfgcmfnlhccnimig?hl=en

Citowise - https://citowise.com/

Hubrisone - https://www.hubrisone.com/ does not work but when I type https://hubrisone.com/ then it works.

**Comment by gitr0n1n** [comment]
Addressed.
