### ISSUE TITLE
ClassicArt display Under Latest applications

### ISSUE THREAD

**Issue by ClassicSavages** [ethereumclassic/ethereumclassic.github.io#789]
Website Link is https://classicart.io

Classicart is the highest quality NFT Marketplace to come to Ethereum Classic. Allows buying and selling of all current projects on the blockchain as well as the ability to turn your artwork into an NFT. Created By youtuber Savageprofits who works to provide transparency on the ETC mainnet.

**Comment by gitr0n1n** [comment]
@ClassicSavages Can you submit a PR for approval to add this to the website lists?

**Comment by gitr0n1n** [comment]
nevermind, this PR was a bit more complex since we needed to add an NFT marketplace section. @ClassicSavages 
https://github.com/ethereumclassic/ethereumclassic.github.io/pull/790
