### ISSUE TITLE
Please kindly help add Mixin in Software Wallets section

### ISSUE THREAD

**Issue by nicolegogo** [ethereumclassic/ethereumclassic.github.io#793]
Hi guys, I'm Nicole from Mixin. 

Mixin wallet has supported ETC for quite a long time and would like to add to ETC website at Software Wallets section: http://ethereumclassic.org/services/wallets

Here is some of our info: https://mixin.one/messenger
https://mixin.space/
https://twitter.com/Mixin_Network

Appreciate the help and would like to contribute more to the community. Anything more needed, just let me know. Thanks.

**Comment by gitr0n1n** [comment]
@nicolegogo Can you submit a PR for review to make this change?

**Comment by nicolegogo** [comment]
> 

Yeah, sure. Thank you.
https://github.com/ethereumclassic/ethereumclassic.github.io/pull/796/files
