### ISSUE TITLE
Is Ethereum Classic ETC Ready to Moon? 

### ISSUE THREAD

**Issue by stonkaholics** [ethereumclassic/ethereumclassic.github.io#798]
`<iframe width="560" height="315" src="https://www.youtube.com/embed/Flqla2LDRYA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

[https://www.youtube.com/watch?v=Flqla2LDRYA]

**Comment by stonkaholics** [comment]
Would love to have this added to the website to help push the project! Thanks for your time and your help

**Comment by gitr0n1n** [comment]
Price Focused, Likely not in the interest of the site, we try to avoid adding the price speculation articles/videos that come out frequently to prevent the end user from having to scroll through content that isn't very relevant past that price prediction.
