### ISSUE TITLE
ETC Labs website down

### ISSUE THREAD

**Issue by sylvaincloutier** [ethereumclassic/ethereumclassic.github.io#801]
Under community - Teams, the etc labs website does not work. Is this team closed now?
https://etclabs.org/
![image](https://user-images.githubusercontent.com/63434273/172505899-52623098-aa93-4f9b-af94-5a8fed6f6555.png)

**Comment by bobsummerwill** [comment]
Yes, they are gone.

**Comment by gitr0n1n** [comment]
Not associated with the community website Closing issue.
