### ISSUE TITLE
Fallback for 404 images 

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/ethereumclassic.github.io#809]
Recent build for #808 failed due to a 404 response from youtube, which in turn fails the build.

https://app.netlify.com/sites/ethereumclassic/deploys/62ae54fd15667e0008942b3c

Fix this by either filtering out items that don't have images (best if the video doesn't exist anymore), or build with a fallback image.

**Comment by w1g0** [comment]
@IstoraMandiri can this issue be closed?
