### ISSUE TITLE
An idea for mitigating 51% attacks

### ISSUE THREAD

**Issue by GodCatHuSky** [ethereumclassic/ethereumclassic.github.io#821]
At the time when Eth switches Pos, Etc may be considered as the best project to replace the traditional Pos proof, but if such a large amount of computing power is switched to Etc, then the possibility of Etc encountering a 51% attack is greatly improved. I have a The idea is to make the newly added computing power gradually release the newly added computing power according to the time curve to solve the attack cost of the attacker. For example, the current computing power of Etc is 22T, if the newly added computing power exceeds the current computing power, it will be A certain kind of scientific calculation yields the release rate of a computing power. Thank you! If there are any unreasonable places, please forgive me. Thank you very much!

**Comment by IstoraMandiri** [comment]
Thank you for contributing, but this repository is specifically for the ETC Website itself, not the Ethereum Classic protocol.

For protocol enhancement proposals, please refer to the https://github.com/ethereumclassic/ECIPs repository.
