### ISSUE TITLE
Add ClassicDAO

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/ethereumclassic.github.io#827]

**Comment by StabeGa** [comment]
# - title: ClassicDAO
#   date: 2022-08-12
#   type: games
#   image: ./images/classicdao.jpg
#   author: StableGaralo
#   teamSite:http://classicdao.io/
#   links:
#     - name: Launch App
#       link: http://classicdao.io/
#     - name: Website
#       link: http://classicdao.io/
#       icon: home
#     - name: Github
#       link: https://github.com/Soteria-Smart-Contracts/ClassicDAO
#       icon: github
#     - name: Twitter
#       link: https://twitter.com/ClassicDao
#       icon: twitter
#     - name: Telegram
#       link: https://t.me/ETCClassicDAO
#       icon: telegram
