### ISSUE TITLE
Show trust score stars on app card 

### ISSUE THREAD

**Issue by w1g0** [ethereumclassic/ethereumclassic.github.io#851]
Now we have to click on a dApp to see the trustscore. Can we have like a star rating on the right lower corner as in the image supplied?
![2022-08-30_21h21_22](https://user-images.githubusercontent.com/67763069/187526937-615a17db-e070-4a38-8ecd-f94793063036.png)

**Comment by w1g0** [comment]
@IstoraMandiri, I would love to help with this but not sure how we can organize since I'm not that proficient in JavaScript. Any ideas?

**Comment by IstoraMandiri** [comment]
I'm not 100% sure about this, as without context the stars look like ratings as opposed to trust scores.

The trust scores are also not really super reliable, so I wouldn't want to make apps look like they are "better" just because they have more "trust" metrics.
