### ISSUE TITLE
Deprecated Apps

### ISSUE THREAD

**Issue by ghost** [ethereumclassic/ethereumclassic.github.io#862]
Should we delete deprecated Apps or move them to a deprecated section? Another option would be to make them greyed out on the current page and have a button to hide/displaying them. In this particular case I have 2 examples in mind: Commonwealth with their tribes game that I recently tested and no longer works and Celsius which have filed for bankruptcy and no longer offers full services. Share your opinions in the comments.

**Comment by w1g0** [comment]
In addition nftcreed.io also seems to no longer support the ETC network upon connecting wallet to the website.

**Comment by TheCrowbill** [comment]
In my opinion, moving deprecated dApps to a separate page would be the best option as it offers archival benefits. Deletion leaves unanswered any question someone may have who is aware of a dApp's existence but not it's deprecated status. The "greying out" option could lead to confusion and would definitely clutter up the active dApp listing.

**Comment by OmniEdge** [comment]
Moving deprecated Dapps might be an never ending job. Its extremely dynamic and how often would the Dapp page be outdated? Might be more efficient to only present a curated list based on above 4 star trust score or another criteria for example....

**Comment by w1g0** [comment]
> Moving deprecated Dapps might be an never ending job. Its extremely dynamic and how often would the Dapp page be outdated? Might be more efficient to only present a curated list based on above 4 star trust score or another criteria for example....

Would you delete deprecated dApps from the list or simply remove the stars from the trust score? Don't completely follow what the desired outcome is from your response.

**Comment by OmniEdge** [comment]
> > Moving deprecated Dapps might be an never ending job. Its extremely dynamic and how often would the Dapp page be outdated? Might be more efficient to only present a curated list based on above 4 star trust score or another criteria for example....
> 
> Would you delete deprecated dApps from the list or simply remove the stars from the trust score? Don't completely follow what the desired outcome is from your response.

To keep it to this current issue: Preference to archive deprecated dApps. Clean and less clutter.

Shower thought: What about only listing 'approved' dApps? Some type of curated listing (subjective) or simply a minimum criteria of 3 to 4 stars trust score or more (objective) before listing them. The desired outcome is to reduce work load on a dynamic page listing and filter out low quality/effort dApps. Not sure what the right balance would be between filtering dApps and a list all laissez faire approach.

**Comment by w1g0** [comment]
> Shower thought: What about only listing 'approved' dApps? Some type of curated listing (subjective) or simply a minimum criteria of 3 to 4 stars trust score or more (objective) before listing them. The desired outcome is to reduce work load on a dynamic page listing and filter out low quality/effort dApps. Not sure what the right balance would be between filtering dApps and a list all laissez faire approach.

@gitr0n1n & @IstoraMandiri ^

**Comment by TheCrowbill** [comment]
From looking at the PR feed from the website, it seems to me that the majority of changes are new dApps being added rather than outdated info being removed. If there is a page already set up for which to move a deprecated link or dApp listing onto then the workload seems minimal after the initial setup. This also has another benefit should something be removed in error which should have been simply updated. It can be recovered from the archival deprecated page easier than recreating the listing.

**Comment by w1g0** [comment]
> From looking at the PR feed from the website, it seems to me that the majority of changes are new dApps being added rather than outdated info being removed. If there is a page already set up for which to move a deprecated link or dApp listing onto then the workload seems minimal after the initial setup. This also has another benefit should something be removed in error which should have been simply updated. It can be recovered from the archival deprecated page easier than recreating the listing.

Currently, I understood that @IstoraMandiri is writing a new website, I don't know what tricks he has up his sleeve. In the meanwhile we can have the discussion here. I lean towards a mashup of all things that you can organize using a filter.
