### ISSUE TITLE
Update @eth_classic with @etc_network 

### ISSUE THREAD

**Issue by brolal** [ethereumclassic/ethereumclassic.github.io#868]
Remove the twitter account @eth_classic, owned by Charles Hoskinson, from the website.
Here, he attacks ETC and speaks about the twitter handler:
https://www.youtube.com/watch?v=03YCJgvPOA4&t=324s

**Comment by w1g0** [comment]
Honestly I think it would still be best to figure out how to get twitter-together working with the @ETC_Network account and if everything is on point, contacting IOHK and see if we can get an API from them and tweet on both accounts with the same process. In both perspectives it is more decentralized.

**Comment by IstoraMandiri** [comment]
I agree with @w1g0 

In any case, I don't think should remove the eth_classic account entirely, at most replacing it on the footer but keeping it in the socials page.
