### ISSUE TITLE
NOW Wallet supports ETC

### ISSUE THREAD

**Issue by alenaign** [ethereumclassic/ethereumclassic.github.io#870]
NOW Wallet is a non-custodial crypto wallet, created by the team of ChangeNOW Crypto Exchange service.

NOW Wallet supports $ETC - the users can securely store, buy it with fiat, and exchange it right in the app. 

May we, please, have NOW Wallet listed [here](https://ethereumclassic.org/services/wallets) among other partner wallets?

Here is a short description of NOW Wallet:
NOW Wallet is a non-custodial mobile cryptocurrency wallet. It allows users to store and exchange crypto assets, choosing from more than 50,000+ trading pairs natively available in the app, including fiat-to-crypto exchanges. NOW Wallet supports 28 blockchains, including the storage of any existing tokens on 7 networks: Ethereum, Binance Smart Chain, Polygon, Avax C-Chain, TRON, Klaytn, and Solana. Our users can also securely store NFTs, connect to dApps with WalletConnect and stake BNB, TRX and NOW Token.

Link to NOW Wallet website: https://walletnow.app/

**Comment by w1g0** [comment]
@alenaign, you can create a PR to be added on the content/services/wallets section. If all the necessary info is provided it can be reviewed and added.
