### ISSUE TITLE
Apps & Protocols Page - Soy Finance Application

### ISSUE THREAD

**Issue by spatialiste** [ethereumclassic/ethereumclassic.github.io#875]
Hello guys, we deployed Soy Finance a few weeks ago, and it's pretty successful among the ETC community, so we would like to apply to have Soy Finance listed on https://ethereumclassic.org/services/apps.

Please find the information below. Please let me know if anything is missing or if you need more information.

Soy Finance logo can be found here:
https://zupimages.net/up/22/37/v6s6.png

- title: SoyFinance
date: 2022-09-12  
image: ./images/soyfinance.png
author: Soy Finance  
authorLink: https://soy.finance/  
verifiedContract: https://blockscout.com/etc/mainnet/address/0x8c5Bba04B2f5CCCe0f8F951D2DE9616BE190070D/contracts#address-tabs
openSource: https://blockscout.com/etc/mainnet/address/0x8c5Bba04B2f5CCCe0f8F951D2DE9616BE190070D/contracts#address-tabs 
audit: https://soy-finance.gitbook.io/soy-finance/soy-products/safety-on-yields/soy-finance-security-audit
teamSite: https://soy-finance.gitbook.io/soy-finance/miscellaneous/callisto-enterprise-team
description: Soy Finance is a decentralized finance platform built with the highest security standards.
type: finance
links:
    - name: Website
      link: https://soy.finance/
      icon: home
    - name: Documentation
      link: https://soy-finance.gitbook.io/soy-finance/
      icon: book
    - name: Github
      link: https://github.com/SoyFinance/
      icon: github
    - name: Twitter
      link: https://twitter.com/Soy_Finance
      icon: twitter
    - name: Telegram
      link: https://t.me/Soy_Finance
      icon: telegram

**Comment by w1g0** [comment]
Hello @spatialiste, this is the PR you requested https://github.com/ethereumclassic/ethereumclassic.github.io/pull/876
When it passes the reviews, your project will be listed on https://ethereumclassic.org/services/apps.

**Comment by spatialiste** [comment]
Thanks a lot @w1g0

**Comment by w1g0** [comment]
FYI: It actually changed to https://github.com/ethereumclassic/ethereumclassic.github.io/pull/877
