### ISSUE TITLE
Spelling issues on home page

### ISSUE THREAD

**Issue by wscott** [ethereumclassic/ethereumclassic.github.io#90]
Under the "Blog" section header "CLASSIC ANNOUNCMENTS"

In the "Miners" section: "We have blockchain explorers for looking transactions and dicvovery blocks"

In the "Developers" section: "Development and maintainance of Ethereum Classic "

In the "Support" section: "Donators and buyers of our t-shirts.."
Better: "People who donate or purchase our t-shirts will receive..."

In the "Features" section: "... put to the vote an idea or a project benefitial for ..."

The "Community" section refers to "Instargam"

At the bottom it suggests you "Subsctibe to news"

**Comment by realcodywburns** [comment]
Sorry it took so long to get to this. I believe all of these have now been corrected

**Comment by arvicco** [comment]
Not ethereumclassic.org community site.
