### ISSUE TITLE
append new ETC RPC 

### ISSUE THREAD

**Issue by mr-arashmousavi** [ethereumclassic/ethereumclassic.github.io#919]
# ETCPlantes

## Hello
Can you help to add RPC?
Thanks
-------------------------------------------------------------
[etcplanets.com](https://etcplanets.com/)

**Comment by w1g0** [comment]
@mr-arashmousavi, add RPC to what?

**Comment by mr-arashmousavi** [comment]
**### hello** 
we want  to add etc rpc to matamask and according to this article [" Public Endpoints "](https://ethereumclassic.org/network/endpoints)
-------------
could you please help

**Comment by w1g0** [comment]
This can be done following this https://ethereumclassic.org/guides/metamask guide.

**Comment by mr-arashmousavi** [comment]
we run over own **ETC** node and we want to people use over **RPC** in metamask

**Comment by w1g0** [comment]
Do you want your RPC url listed here?

![2022-10-08_21h15_03](https://user-images.githubusercontent.com/67763069/194723866-a4c41585-39d9-481f-b0f4-b13888f8d795.png)

**Comment by mr-arashmousavi** [comment]
yes

**Comment by mr-arashmousavi** [comment]
And we wanted guidance in the field of activation in Metamask
Metamask in some browsers
eth_chainId error
gives

**Comment by w1g0** [comment]
Fork this repo, edit this https://github.com/ethereumclassic/ethereumclassic.github.io/blob/master/content/network/endpoints/index.en.yaml file and create a pull request into master branch. Once reviewed and approved it will be added in this list.

Guidance for MetaMask I personally can provide if anyone here, but maybe seek assistance in on their GitHuB?
https://github.com/MetaMask/metamask-docs

cc @IstoraMandiri, @gitr0n1n

**Comment by IstoraMandiri** [comment]
Fixed in #920
