### ISSUE TITLE
Add Community Calls to the website

### ISSUE THREAD

**Issue by d-a8564** [ethereumclassic/ethereumclassic.github.io#936]
Can we update the latest community calls on the website? sorry, I'm not very familiar with github

Ethereum Classic Community Calls: https://www.youtube.com/channel/UCp07VPnC1ejyAp5gMvvA4dw

thank you

**Comment by w1g0** [comment]
Hello @d-a8564, they are here https://ethereumclassic.org/community/channels#media
unless your question is to add it here https://ethereumclassic.org/videos

**Comment by d-a8564** [comment]
Yes, I wish we could add the last 4 calls here https://ethereumclassic.org/videos

**Comment by d-a8564** [comment]
There are also educational videos about Ethereum Classic from the Emerald youtube channel that have been made recently, I think it could be good to add them.
For exemple
What is WETC: https://www.youtube.com/watch?v=xJtqXMBz0UA
The Ethereum Classic Monetary Policy Explained: https://www.youtube.com/watch?v=2zXqFTFJLic

**Comment by w1g0** [comment]
If you want maybe we can propose a demonstration during the Community Calls on how to make a PR?
It are all great suggestions imo.

**Comment by w1g0** [comment]
Basically you fork the "https://github.com/ethereumclassic/ethereumclassic.github.io" repo and edit the "https://github.com/ethereumclassic/ethereumclassic.github.io/blob/master/content/videos/videos.collection.en.yaml" file. The format is explained with the # in front it omits the code. When it's saved you can Pull a Request from your own branch (personal repository) into the master branch (ETC repository). You can do no harm by trying.

**Comment by d-a8564** [comment]
I'll try, thank you @w1g0

**Comment by w1g0** [comment]
The interface can a bit daunting so check some online tutorials if it is unclear, when your still stuck just drop a line here or on Discord 😉

**Comment by w1g0** [comment]
https://github.com/ethereumclassic/ethereumclassic.github.io/pull/938
