### ISSUE TITLE
Add Project - Shiba Classic

### ISSUE THREAD

**Issue by shibcmemes** [ethereumclassic/ethereumclassic.github.io#946]
Hello 👋, I am danoz and I am self appointed Minister of Engineering Maximal Experiences (MEMEs) at Shiba Classic. 

As discussed with @IstoraMandiri in https://github.com/ethereumclassic/tweets-etc_network/pull/116#issuecomment-1287642884 < here yesterday - I am requesting to have Shiba Classic added to ethereumclassic.org

Website: https://www.shibaclassic.sc/ 

Audit: https://twitter.com/SoteriaSC/status/1561793005530611713 = https://www.docdroid.net/RpaLygS/soteriasc-shibaclassic-smart-contract-security-review-docx

GitHub for Shiba Classic contract: https://github.com/Shiba-Classic-ETC/Shiba-Classic-Contract-Code

HebeSwap LP token held by 0x..dEaD: https://blockscout.com/etc/mainnet/token/0xcCD8dc89EE29D65802f36D75E458CA6F6b18493C/token-holders

Twitter: https://twitter.com/shibctokenetc

Telegram: https://t.me/ShibCtokenERC

Linktree: https://linktr.ee/shibctoken (for anything else you could possibly need).

Info on the NFT we're launching soon with details about the marketplace, etc: https://twitter.com/TheClassicDawgs

Both of which we'd like to also have added when they go live.

If there's anything else I've missed, or anything else you'd like to know, just hit me up.

**Comment by IstoraMandiri** [comment]
Sure thing, I'll add this soon.

Thank you for your service, Minister.

**Comment by shibcmemes** [comment]
Much appreciated, thank you🖖
