### ISSUE TITLE
Shiba Classic Trust Level Outdated/Incorrect

### ISSUE THREAD

**Issue by shibcmemes** [ethereumclassic/ethereumclassic.github.io#964]
gm, good afternoon and gn - depending on where you are!

Thank you for adding Shiba Classic to the website, that is really appreciated.

I am wondering if our trust level is incorrect or perhaps outdated - I know that it was a late addition that our contract is open source and verified as the one on chain.

It does link appropriately to GitHub: https://github.com/Shiba-Classic-ETC/Shiba-Classic-Contract-Code

That is verified as the contract on chain: https://blockscout.com/etc/mainnet/address/0x1FDc495289B590e78d455cf7faa6cd804de5Cbc1/contracts#address-tabs 

![image](https://user-images.githubusercontent.com/70056410/198858980-9d1d2297-02db-4557-b9d4-ad9594904dcc.png)

Thank you again

**Comment by IstoraMandiri** [comment]
Thanks for the post. For the Open Source check, the project must meet the definitions of an Open Source project.

This includes having an Open Source license, as well as the source code (the original project files used to create the contract).

In this case, the repository you have provided does not contain an open source license, and only contains the concatenated contract output, not the source files.

Sorry if this isn't clear yet, we are working on docs.

Ref #892

**Comment by shibcmemes** [comment]
Gotcha - that makes a lot of sense. Thank you for this info!
