### ISSUE TITLE
Display Machine Translations?

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereumclassic/ethereumclassic.github.io#983]
So currently we have auto-translated the website into many languages.

https://etc-i18n.netlify.com

These auto-translations are imperfect, so are not merged into master yet. We could merge them into master (i.e. make them visible on https://etheruemclassic.org) to incentivize contributions (see readme).

This might look bad and might confuse people if the translations don't make sense, but for translated pages we can show the banner at the top explaining that they're machine translations and would like contributions.

Before we do this I could also manually go through the machine translations on crowdin to fix ML mishaps (links and some formatting issues).

Alternatively, we could wait until the machine-translations are proof read by a human and enable each locale as they are approved.

Thoughts?

**Comment by DonaldMcIntyre** [comment]
At ETC Coop we are writing posts in english and then a team member translates manually to Chinese. Then, we post them in the main website one after the other as consecutive posts. 

The other option is to just have the site in english and have people use Google automatic Translate as it happens rto me when I go to foreign sites.

**Comment by w1g0** [comment]
Enabling translations that are not proof read doesn't make much sense as people can achieve the same outcome by installing the Google translate browser plugin. The only thing you achieve is making your website look unprofessional imo.

**Comment by TheCrowbill** [comment]
> Enabling translations that are not proof read doesn't make much sense as people can achieve the same outcome by installing the Google translate browser plugin. The only thing you achieve is making your website look unprofessional imo.

Given that the banner @IstoraMandiri suggests is prominently displayed on every unproofed page and clearly states that we only publish unproofed material in order to recruit translation help and encourage broader participation, I see nothing unprofessional about it.

It is a reasonable way for unfunded volunteers to recruit help since there is no headhunter budget from which to hire a translation team.

I say turn it all on.

**Comment by w1g0** [comment]
Ok, you guys convinced me 👍
